var Imported = Imported || {};
Imported.TEW_Constants = true;
var TEW = TEW || {};

TEW.ARMORS = TEW.ARMORS || {
    SOFT_KIT: {
        name: "Soft Kit",
        icon: TEW.ICONS_IDS.ARMOR_LIGHT_BODY_SLOT,
        group: "SOFT_KIT",
        groupLabel: "Soft kit",
        price: "0/18/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        penalty: [],
        locations: ["ARMS", "BODY", "LEGS"],
        ap: 0,
        qualities: [],
        forbiddenWith: [],
        description: "Description has to be done."
    },
    REINFORCED_SOFT_KIT: {
        name: "Reinforced Soft Kit",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_BODY_SLOT,
        group: "SOFT_KIT",
        groupLabel: "Soft kit",
        price: "2/0/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        penalty: [],
        locations: ["ARMS", "BODY", "LEGS"],
        ap: 1,
        qualities: ["PARTIAL", "REINFORCED"],
        forbiddenWith: [],
        description: "Description has to be done."
    },
    LEATHER_JACK: {
        name: "Leather Jack",
        icon: TEW.ICONS_IDS.ARMOR_LIGHT_BODY_SLOT,
        group: "BOILED_LEATHER",
        groupLabel: "Boiled leather",
        price: "0/12/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        penalty: [],
        locations: ["ARMS", "BODY"],
        ap: 1,
        qualities: [],
        forbiddenWith: ["CHAINMAIL", "PLATE"],
        description: "Description has to be done."
    },
    LEATHER_JERKIN: {
        name: "Leather Jerkin",
        icon: TEW.ICONS_IDS.ARMOR_LIGHT_BODY_SLOT,
        group: "BOILED_LEATHER",
        groupLabel: "Boiled leather",
        price: "0/10/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        penalty: [],
        locations: ["BODY"],
        ap: 1,
        qualities: [],
        forbiddenWith: ["CHAINMAIL", "PLATE"],
        description: "Description has to be done."
    },
    LEATHER_LEGGINGS: {
        name: "Leather Leggings",
        icon: TEW.ICONS_IDS.ARMOR_LIGHT_LEGS_SLOT,
        group: "BOILED_LEATHER",
        groupLabel: "Boiled leather",
        price: "0/14/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        penalty: [],
        locations: ["LEGS"],
        ap: 1,
        qualities: [],
        forbiddenWith: ["CHAINMAIL", "PLATE"],
        description: "Description has to be done."
    },
    LEATHER_SKULLCAP: {
        name: "Leather Skullcap",
        icon: TEW.ICONS_IDS.ARMOR_LIGHT_HEAD_SLOT,
        group: "BOILED_LEATHER",
        groupLabel: "Boiled leather",
        price: "0/8/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        penalty: [],
        locations: ["HEAD"],
        ap: 1,
        qualities: [],
        forbiddenWith: ["CHAINMAIL", "PLATE"],
        description: "Description has to be done."
    },
    CHAINMAIL_CHAUSSES: {
        name: "Chainmail Chausses",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_LEGS_SLOT,
        group: "CHAINMAIL",
        groupLabel: "Chainmail",
        price: "2/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        penalty: [{ STEALTH: "-10" }],
        locations: ["LEGS"],
        ap: 2,
        qualities: [],
        forbiddenWith: ["BOILED_LEATHER", "PLATE"],
        description: "Description has to be done."
    },
    CHAINMAIL_COAT: {
        name: "Chainmail Coat",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_BODY_SLOT,
        group: "CHAINMAIL",
        groupLabel: "Chainmail",
        price: "3/0/0",
        enc: 4,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        penalty: [{ STEALTH: "-10" }],
        locations: ["ARMS", "BODY"],
        ap: 2,
        qualities: [],
        forbiddenWith: ["BOILED_LEATHER", "PLATE"],
        description: "Description has to be done."
    },
    CHAINMAIL_COIF: {
        name: "Chainmail Coif",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_HEAD_SLOT,
        group: "CHAINMAIL",
        groupLabel: "Chainmail",
        price: "1/0/0",
        enc: 2,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        penalty: [{ PERCEPTION: "-10", STEALTH: "-10" }],
        locations: ["HEAD"],
        ap: 2,
        qualities: ["PARTIAL"],
        forbiddenWith: ["BOILED_LEATHER", "PLATE"],
        description: "Description has to be done."
    },
    CHAINMAIL_SHIRT: {
        name: "Chainmail Shirt",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_BODY_SLOT,
        group: "CHAINMAIL",
        groupLabel: "Chainmail",
        price: "2/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        penalty: [{ STEALTH: "-10" }],
        locations: ["BODY"],
        ap: 2,
        qualities: [],
        forbiddenWith: ["BOILED_LEATHER", "PLATE"],
        description: "Description has to be done."
    },
    BRIGANDINE_JACK: {
        name: "Brigandine Jack",
        icon: TEW.ICONS_IDS.ARMOR_LIGHT_BODY_SLOT,
        group: "BRIGANDINE",
        groupLabel: "Brigandine",
        price: "3/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        penalty: [],
        locations: ["ARMS", "BODY"],
        ap: 2,
        qualities: ["OVERCOAT"],
        forbiddenWith: ["PLATE"],
        description: "Description has to be done."
    },
    BRIGANDINE_JERKIN: {
        name: "Brigandine Jerkin",
        icon: TEW.ICONS_IDS.ARMOR_LIGHT_BODY_SLOT,
        group: "BRIGANDINE",
        groupLabel: "Brigandine",
        price: "2/0/0",
        enc: 2,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        penalty: [],
        locations: ["BODY"],
        ap: 2,
        qualities: ["OVERCOAT"],
        forbiddenWith: ["PLATE"],
        description: "Description has to be done."
    },
    BREASTPLATE: {
        name: "Breastplate",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_BODY_SLOT,
        group: "BREASTPLATE",
        groupLabel: "Breastplate",
        price: "10/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        penalty: [],
        locations: ["BODY"],
        ap: 3,
        qualities: ["IMPENETRABLE", "OVERCOAT", "WEAKPOINTS"],
        forbiddenWith: ["PLATE"],
        description: "Description has to be done."
    },
    BRACERS: {
        name: "Bracers",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_ARMS_SLOT,
        group: "PLATE",
        groupLabel: "Plate",
        price: "8/0/0",
        enc: 3,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        penalty: [],
        locations: ["ARMS"],
        ap: 3,
        qualities: ["IMPENETRABLE", "REQUIRES_KIT", "WEAKPOINTS"],
        forbiddenWith: ["BOILED_LEATHER", "CHAINMAIL", "BRIGANDINE"],
        description: "Description has to be done."
    },
    OPEN_HELM: {
        name: "Open Helm",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_HEAD_SLOT,
        group: "PLATE",
        groupLabel: "Plate",
        price: "2/0/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        penalty: [{ PERCEPTION: "-10" }],
        locations: ["HEAD"],
        ap: 3,
        qualities: ["PARTIAL"],
        forbiddenWith: ["BOILED_LEATHER", "CHAINMAIL", "BRIGANDINE"],
        description: "Description has to be done."
    },
    PLATE_LEGGINGS: {
        name: "Plate Leggings",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_LEGS_SLOT,
        group: "PLATE",
        groupLabel: "Plate",
        price: "10/0/0",
        enc: 3,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        penalty: [{ STEALTH: "-10" }],
        locations: ["LEGS"],
        ap: 3,
        qualities: ["IMPENETRABLE", "REQUIRES_KIT", "WEAKPOINTS"],
        forbiddenWith: ["BOILED_LEATHER", "CHAINMAIL", "BRIGANDINE"],
        description: "Description has to be done."
    },
    GREAT_HELM: {
        name: "Great Helm",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_HEAD_SLOT,
        group: "PLATE",
        groupLabel: "Plate",
        price: "2/0/0",
        enc: 2,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        penalty: [{ PERCEPTION: "-20" }],
        locations: ["HEAD"],
        ap: 3,
        qualities: ["IMPENETRABLE", "WEAKPOINTS"],
        forbiddenWith: ["BOILED_LEATHER", "CHAINMAIL", "BRIGANDINE"],
        description: "The Great Helm is the archetypal form of a fully enclosed metal helmet. They are considered old fashioned in Tilea and the Empire but are still common in Bretonnia. Early examples of these helmets had a square top. Later designs tend to have a conical top which lessens the impact of hammers and swords."
    },
    BASCINET: {
        name: "Bascinet",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_HEAD_SLOT,
        group: "PLATE",
        groupLabel: "Plate",
        price: "3/0/0",
        enc: 2,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        penalty: [{ PERCEPTION: "-20" }],
        locations: ["HEAD"],
        ap: 3,
        qualities: ["IMPENETRABLE", "VISOR", "WEAKPOINTS"],
        forbiddenWith: ["BOILED_LEATHER", "CHAINMAIL", "BRIGANDINE"],
        description: "The Bascinet typically incorporates a conical visor, leading it to be known as a ‘pigs-snout’ helmet by many soldiers. This design provides additional protection against missile fire, as slingshots and arrows are deflected by the conical visor. If missile fire strikes the wearer of a Bascinet, and originates from in front of the wearer, then the helmet provides 4 APs rather than 3."
    },
    ARMET: {
        name: "Armet",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_HEAD_SLOT,
        group: "PLATE",
        groupLabel: "Plate",
        price: "3/0/0",
        enc: 2,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        penalty: [{ PERCEPTION: "-20" }],
        locations: ["HEAD"],
        ap: 3,
        qualities: ["IMPENETRABLE", "VISOR", "WEAKPOINTS"],
        forbiddenWith: ["BOILED_LEATHER", "CHAINMAIL", "BRIGANDINE"],
        description: "The Armet is a Tilean design which fits closely on the head, being narrower around the neck. To facilitate the snug fit the helmet has an integral mechanism that must be worked to open and close it. The exacting design of the Armet means that it can withstand blows that might damage other helmets. Every time the helmet might lose a point of AP, roll on the Armet Damage table."
    }, 
    SALLET: {
        name: "Sallet",
        icon: TEW.ICONS_IDS.ARMOR_HEAVY_HEAD_SLOT,
        group: "PLATE",
        price: "4/0/0",
        enc: 2,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        penalty: [{
            PERCEPTION: "-20"
        }],
        locations: ["HEAD"],
        ap: 3,
        qualities: ["IMPENETRABLE","VISOR","WEAKPOINTS"],
        forbiddenWith: ["BOILED_LEATHER","CHAINMAIL","BRIGANDINE"],
        description: "The Sallet is typified by having heavy plates projecting over the neck to the back, and being combined with separate pieces, either a gorget or bevor, to provide protection to the throat, chin, and face. A wearer of a Sallet who takes a Critical Hit to the head will take 1 less Wound from the Critical Hit than they otherwise would."
    }
};

// TODO order in inventory ?
TEW.ARMOR_IDS = Object.keys(TEW.ARMORS).sort((a, b) => a.localeCompare(b));
TEW.ARMORS_ARRAY = Object.entries(TEW.ARMORS).sort((a, b) => a[0].localeCompare(b[0]));