import { DataActor, DataClass } from "./data/RPG_Actor";
import { DataPlugin, DataAnimation, DataState, DataTileset } from "./data/RPG_Core";
import { DataEnemy, DataTroop } from "./data/RPG_Enemy";
import { DataCommonEvent } from "./data/RPG_Event";
import { DataArmor, DataItem, DataSkill, DataWeapon } from "./data/RPG_Item";
import { DataMap, DataMapInfo } from "./data/RPG_Map";
import { DataSystem } from "./data/RPG_System";
import { Game_Actors } from "./objects/Game_Actors";
import { Game_Map } from "./objects/Game_Map";
import { Game_Message } from "./objects/Game_Message";
import { Game_Party } from "./objects/Game_Party";
import { Game_Player } from "./objects/Game_Player";
import { Game_Screen } from "./objects/Game_Screen";
import { Game_SelfSwitches } from "./objects/Game_SelfSwitches";
import { Game_Switches } from "./objects/Game_Switches";
import { Game_System } from "./objects/Game_System";
import { Game_Temp } from "./objects/Game_Temp";
import { Game_Timer } from "./objects/Game_Timer";
import { Game_Troop } from "./objects/Game_Troop";
import { Game_Variables } from "./objects/Game_Variables";

export declare var $plugins:DataPlugin[];

export declare var $dataActors:DataActor[];
export declare var $dataAnimations:DataAnimation[];
export declare var $dataArmors:DataArmor[];
export declare var $dataClasses:DataClass[];
export declare var $dataCommonEvents:DataCommonEvent[];
export declare var $dataEnemies:DataEnemy[];
export declare var $dataItems:DataItem[];
export declare var $dataMap:DataMap;
export declare var $dataMapInfos:DataMapInfo[];
export declare var $dataSkills:DataSkill[];
export declare var $dataStates:DataState[];
export declare var $dataSystem:DataSystem;
export declare var $dataTilesets:DataTileset[];
export declare var $dataTroops:DataTroop[];
export declare var $dataWeapons:DataWeapon[];

export declare var $gameActors:Game_Actors;
export declare var $gameMap:Game_Map;
export declare var $gameMessage:Game_Message;
export declare var $gameParty:Game_Party;
export declare var $gamePlayer:Game_Player;
export declare var $gameScreen:Game_Screen;
export declare var $gameSelfSwitches:Game_SelfSwitches;
export declare var $gameSwitches:Game_Switches;
export declare var $gameSystem:Game_System;
export declare var $gameTemp:Game_Temp;
export declare var $gameTimer:Game_Timer;
export declare var $gameTroop:Game_Troop;
export declare var $gameVariables:Game_Variables;
