// $PluginCompiler TEW_Constants.js 2

import TEW from "../types/tew";

// $StartCompilation
TEW.DATABASE.ICONS = {};
TEW.DATABASE.ICONS.SET = {
    // Item groups
    ITEM_CLOTHES : 154,
    ITEM_FOOD : 265,
    ITEM_TOOLS : 216,
    ITEM_BOOKS : 189,
    ITEM_DRUGS : 219,

    // Item availability
    AVAILABILITY_COMMON : 89,
    AVAILABILITY_SCARCE : 88,
    AVAILABILITY_RARE : 87,
    AVAILABILITY_EXOTIC : 90,

    // Weapon Equipped
    EQUIPPED_MAIN_HAND: 28,
    EQUIPPED_SECOND_HAND: 29,

    // Weapons
    WEAPON_KNIFE: 320,
    WEAPON_SWORD: 321,
    WEAPON_FLAIL: 322,
    WEAPON_AXE: 323,
    WEAPON_WHIP: 324,
    WEAPON_WAND: 325,
    WEAPON_BOW: 326,
    WEAPON_CROSSBOW: 327,
    WEAPON_PISTOL: 328,
    WEAPON_CLAW: 329,
    WEAPON_GAUNTLET: 330,
    WEAPON_SPEAR: 331,
    WEAPON_SCEPTER1: 332,
    WEAPON_SCEPTER2: 333,
    WEAPON_MACE: 334,
    WEAPON_CHAINS: 335,
    WEAPON_ENERGY_SWORD: 336,
    WEAPON_PIPE: 337,
    WEAPON_SLING: 338,
    WEAPON_SHOTGUN: 339,
    WEAPON_RIFLE: 340,
    WEAPON_CHAINSAW: 341,
    WEAPON_FIRE_BALL: 342,
    WEAPON_BREAKER: 343,
    WEAPON_KATANA: 344,
    WEAPON_BOOK: 345, 
    WEAPON_SCYTHE: 346,
    WEAPON_SABER: 347,
    WEAPON_FOIL: 348,
    WEAPON_RAPIER: 349,
    WEAPON_STAFF: 350, 
    WEAPON_BOMB: 351,   
    WEAPON_SHIELD: 352,

    // Armor equipped
    EQUIPPED_ARMOR: 30,

    // Armors
    ARMOR_LIGHT_HEAD_SLOT: 355,
    ARMOR_HEAVY_HEAD_SLOT: 356,
    ARMOR_LIGHT_BODY_SLOT: 360,
    ARMOR_HEAVY_BODY_SLOT: 361,
    ARMOR_LIGHT_LEGS_SLOT: 364,
    ARMOR_HEAVY_LEGS_SLOT: 365,
    ARMOR_LIGHT_ARMS_SLOT: 366,
    ARMOR_HEAVY_ARMS_SLOT: 367,
}
