// $PluginCompiler TEW_Constants.js

// ----------------------

// File: TEW_Weapons.ts
// Author: Ersokili, 7evy, Sebibebi67
// Date: 12/04/2025
// Description: This file contains the Weapons constants for the TEW. It is used to define the weapons in the game, their stats, damage, and other properties. The constants are used throughout the game to reference the weapons and their properties.

// ----------------------
// Imports
// ----------------------

import { WeaponGroup, WeaponGroupLabel, WeaponQuality, Availability } from "../_types/enum";
import TEW from "../_types/tew";

// ----------------------
// $StartCompilation
// ----------------------

TEW.DATABASE.WEAPONS = {};
// #region ====== WEAPONS MELEE SET === //
TEW.DATABASE.WEAPONS.MELEE_SET =  {
    AXE: {
        name: "Axe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 120,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.HACK, WeaponQuality.UNBALANCED],
        description: "Much beloved of Dwarfs, the axe is not as agile in the hand as a sword but the heavy cleaving head can make a mess of armour and shields."
    },
    BALLOCK_KNIFE: {
        name: "Ballock Knife",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 192,
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING, WeaponQuality.PRECISE],
        description: "The short, slim blade of a ballock knife makes for a poor weapon, unless you have a heavily armoured opponent at your mercy."
    },
    CLUB: {
        name: "Club",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 48,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.UNDAMAGING, WeaponQuality.UNBALANCED],
        description: "Clubs are as often found as they are crafted."
    },
    DAGGER: {
        name: "Dagger",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 192,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "These blades are crafted specifically for fighting."
    },
    IMPROVISED_WEAPON: {
        name: "Improvised Weapon",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PIPE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 0,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.UNDAMAGING, WeaponQuality.UNBALANCED],
        description: "Hard and heavy items that are not intended to be used as a weapon may still serve in a desperate moment. This entry covers such items as chair legs, rocks, snooker cues, and bottles."
    },
    KNIFE: {
        name: "Knife",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 96,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.UNDAMAGING],
        description: "This entry covers short, sharp blades intended for purposes other than fighting, such as kitchen or hunting knives."
    },
    MACE: {
        name: "Mace",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 180,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.PUMMEL, WeaponQuality.UNBALANCED],
        description: "The typical mace is a metal shaft with a heavy head shaped in flanges or spiked protrusions. Whilst it is less wieldy than a sword it inflicts concussive blows."
    },
    MILITARY_PICK: {
        name: "Military Pick",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 180,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.PENETRATING, WeaponQuality.UNBALANCED],
        description: "Crude picks are little more than a metal spike on the end of a stick, though better made weapons are fashioned from steel. They are not agile weapons but are well designed to crack armour."
    },
    SCIMITAR: {
        name: "Scimitar",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SABER,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 240,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.SLASH_1],
        description: "Popular in the east of the Empire, Kislev and Araby, the scimitar has a curved blade which can inflict terrible cutting wounds. Its design does compromise the welder's ability to lunge and thrust, meaning that even though scimitars are a similar length to straight swords they have a shorter reach."
    },
    SWORD: {
        name: "Sword",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SWORD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 240,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [],
        description: "The sword is the weapon by which all others are measured. A quality sword has a needle point tip for thrusting, a blade that is razor sharp to either side, and is balanced so that the weight is close to the hand, making it agile for attack and defence."
    },
    WARHAMMER: {
        name: "Warhammer",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 240,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.PENETRATING, WeaponQuality.PUMMEL, WeaponQuality.UNBALANCED],
        description: "Warhammers come in several designs, but typically have a flat heavy head on one side for inflicting pummelling damage, and a spiked point on the other for penetrating armour."
    },
    SHIELD_BUCKLER: {
        name: "Shield (Buckler)",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHIELD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 218,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        strBonus: true,
        longReach: false,
        damage: 1,
        qualities: [WeaponQuality.SHIELD_1, WeaponQuality.DEFENSIVE, WeaponQuality.UNDAMAGING],
        description: "A small shield to save you from harm."
    },
    SHIELD: {
        name: "Shield",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHIELD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 480,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.SHIELD_2, WeaponQuality.DEFENSIVE, WeaponQuality.UNDAMAGING],
        description: "A regular shield, ideal for close combat."
    },
    SHIELD_LARGE: {
        name: "Shield (Large)",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHIELD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 720,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.SHIELD_3, WeaponQuality.DEFENSIVE, WeaponQuality.UNDAMAGING],
        description: "A large shield to protect you from all enemies"
    },
    PAVISE: {
        name: "Pavise",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHIELD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 900,
        enc: 4,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.SHIELD_5],
        description: "The pavise is a large shield carried by crossbowmen to provide shelter on the battlefield as they reload. Roughly 4 feet tall and often painted with the unit's coat of arms, the crossbowman plants the pavise on the ground like a personal wall."
    },
    CAVALRY_HAMMER: {
        name: "Cavalry Hammer",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.CAVALRY,
        groupLabel: WeaponGroupLabel.CAVALRY,
        price: 720,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.PUMMEL],
        description: "Cavalry hammers are large, weighty weapons, favoured by the Knights of the White Wolf. On foot, they may be used with the Melee (Two-Handed) skill."
    },
    DEMI_LANCE: {
        name: "Demi-Lance",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.CAVALRY,
        groupLabel: WeaponGroupLabel.CAVALRY,
        price: 240,
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.IMPACT, WeaponQuality.IMPALE],
        description: "Lances resemble spears, but with a weighty grip designed to brace the weapon against the arm and chest of a charging knight. The demi-lance is similar, but shorter and lighter."
    },
    LANCE: {
        name: "Lance",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.CAVALRY,
        groupLabel: WeaponGroupLabel.CAVALRY,
        price: 240,
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: [WeaponQuality.IMPACT, WeaponQuality.IMPALE],
        description: "Lances resemble spears, but with a weighty grip designed to brace the weapon against the arm and chest of a charging knight. The demi-lance is similar, but shorter and lighter."
    },
    SABRE: { //TODO
        name: "Sabre",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SABER,
        group: WeaponGroup.CAVALRY,
        groupLabel: WeaponGroupLabel.CAVALRY,
        price: 120,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.SLASH_1],
        description: "The sabre is similar to the scimitar, but a little longer and straighter. It may be used on foot with Melee (Basic)."
    },
    FOIL: {
        name: "Foil",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FOIL,
        group: WeaponGroup.FENCING,
        groupLabel: WeaponGroupLabel.FENCING,
        price: 1200,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.FAST, WeaponQuality.IMPALE, WeaponQuality.PRECISE, WeaponQuality.UNDAMAGING],
        description: "The foil is a light sword with a blade like a thin sharpened spike. They are light in the hand with a balance at the hilt, but short of a dramatic lunge they tend to only inflict small prinking injuries."
    },
    RAPIER: {
        name: "Rapier",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_RAPIER,
        group: WeaponGroup.FENCING,
        groupLabel: WeaponGroupLabel.FENCING,
        price: 1200,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.FAST, WeaponQuality.IMPALE],
        description: "The rapier is a long thin sword. Like the foil it comes to a fine point for thrusting, but the sharp blade retains much of the cutting power of a traditional sword."
    },
    SMALLSWORD: {
        name: "Smallsword",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FOIL,
        group: WeaponGroup.FENCING,
        groupLabel: WeaponGroupLabel.FENCING,
        price: 960,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.FAST, WeaponQuality.IMPALE, WeaponQuality.PRECISE],
        description: "A light version of the foil. The smallsword is not considered a serious weapon and is more often employed in sporting contests or duels to first blood. Smallswords with blunt tips and blades are often used as sport weapons, gaining the Undamaging Flaw."
    },
    SPIKED_GAUNTLET: {
        name: "Spiked Gauntlet",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 480,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.IMPALE, WeaponQuality.UNBALANCED],
        description: "A spiked gauntlet may be purchased as part of a set of plate armour for the arm. Add the price of the spiked gauntlet to that of the armour, but just use the Encumbrance of the armour itself; the spiked gauntlet does not involve significant additional weight or bulk."
    },
    BOAT_HOOK: {
        name: "Boat Hook",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 72,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.TRIP, WeaponQuality.UNDAMAGING],
        description: "Hooks are used by stevedores to help with loading and securing cargoes, but they can make vicious weapons if wielded with intent."
    },
    GARROTE: {
        name: "Garrote",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CHAINS,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 12,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.ENTANGLE, WeaponQuality.SLOW, WeaponQuality.UNBALANCED, WeaponQuality.UNDAMAGING],
        description: "A garotte is a length of cord or wire intended to be slipped around the neck and drawn tight with the wielder's hands."
    },
    UNARMED: {
        name: "Unarmed",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 0,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: [WeaponQuality.UNDAMAGING],
        description: "Your bare fists."
    },
    KNUCKLEDUSTERS: {
        name: "Knuckledusters",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 30,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "Brass knuckles can add considerable power to a fighter's strikes, but a set of knuckledusters could be improvised from textiles and tools."
    },
    LOCKED_GAUNTLET: {
        name: "Locked Gauntlet",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CLAW,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 240,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.UNDAMAGING],
        description: "A locked gauntlet is formed from plates of steel that encase the fist and can be held shut with a screw or catch. Whilst the gauntlet may be used as a Brawling Weapon it is more commonly employed as a method to ensure that the wielder does not drop a weapon held in the gauntleted hand."
    },
    SAP: {
        name: "Sap",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 12,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.PUMMEL, WeaponQuality.UNBALANCED, WeaponQuality.UNDAMAGING],
        description: "A well-made Sap consists of a leather or textile sheath stuffed with sand, musket balls, iron rods or similar small heavy items."
    },
    GRAIN_FLAIL: {
        name: "Grain Flail",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FLAIL,
        group: WeaponGroup.FLAIL,
        groupLabel: WeaponGroupLabel.FLAIL,
        price: 120,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.DISTRACT, WeaponQuality.IMPRECISE, WeaponQuality.WRAP],
        description: "The common adage that peasants can beat their ploughshares into weapons is overstated, but a grain flail in the right hands is dangerous. A grain flail consists of a wooden handle connected to a heavy stick, known as a swipple, by a length of chain."
    },
    FLAIL: {
        name: WeaponGroupLabel.FLAIL,
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FLAIL,
        group: WeaponGroup.FLAIL,
        groupLabel: WeaponGroupLabel.FLAIL,
        price: 480,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DISTRACT, WeaponQuality.WRAP],
        description: "Flails made for the battlefield incorporate metal swipples and reinforcements to the handle, enabling them to pack a heftier punch."
    },
    MILITARY_FLAIL: {
        name: "Military Flail",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FLAIL,
        group: WeaponGroup.FLAIL,
        groupLabel: WeaponGroupLabel.FLAIL,
        price: 720,
        enc: 2,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: [WeaponQuality.DISTRACT, WeaponQuality.IMPRECISE, WeaponQuality.TIRING, WeaponQuality.WRAP],
        description: "Flails made for the battlefield incorporate metal swipples and reinforcements to the handle, enabling them to pack a heftier punch."
    },
    CLOAK: {
        name: "Cloak",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CHAINS,
        group: WeaponGroup.PARRY,
        groupLabel: WeaponGroupLabel.PARRY,
        price: 120,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: [WeaponQuality.ENTANGLE, WeaponQuality.DEFENSIVE, WeaponQuality.UNDAMAGING],
        description: "Some experts in fencing and parrying recommend keeping a cloak of heavy fabric handy. When bunched around the arm it can be used to distract opponents or divert their attacks. It can even be flung over an opponent in the hope that they will become lost in its folds. However, cloaks are not well suited for entangling attacks. When making a Test to see if an opponent becomes entangled in a cloak, the cloak has a Strength of 25."
    },
    MAIN_GAUCHE: {
        name: "Main Gauche",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.PARRY,
        groupLabel: WeaponGroupLabel.PARRY,
        price: 240,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.DEFENSIVE],
        description: "A main gauche is a specially designed dagger used in fencing. It is so called because it is typically wielded in the left hand by right-handed fighters to complement a fencing weapon used as a primary weapon. A fighter with no Melee (Parrying) Skill could still use a main gauche, though they would call it a dagger and it would lose the Defensive Quality."
    },
    SWORDBREAKER: {
        name: "Swordbreaker",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BREAKER,
        group: WeaponGroup.PARRY,
        groupLabel: WeaponGroupLabel.PARRY,
        price: 270,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.TRAP_BLADE],
        description: "These weapons are designed like long daggers or sturdy shortswords. Their blades are thicker than those of swords, and along one side several deep grooves are cut into the blade. This design greatly compromises the weapon's ability to cut, but enables a skilled user to catch an opponent's blade and hold it fast."
    },
    WEIGHTED_NET: {
        name: "Weighted Net",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CHAINS,
        group: WeaponGroup.PARRY,
        groupLabel: WeaponGroupLabel.PARRY,
        price: 120,
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: [WeaponQuality.ENTANGLE, WeaponQuality.DEFENSIVE, WeaponQuality.SHIELD_1, WeaponQuality.SLOW, WeaponQuality.UNDAMAGING, WeaponQuality.WRAP],
        description: "A weighted net is cumbersome and clumsy, but capable of severely impeding an opponent's fighting ability when used in a timely fashion. When making a Test to see if an opponent becomes entangled in a weighted net, the net has a Strength of 55."
    },
    AHLSPIESS: {
        name: "Ahlspiess",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "The ahlspiess mounts a long thin spike on a spear shaft, compromising its ability to inflict cutting wounds in order to better penetrate armour."
    },
    BILL: {
        name: "Bill",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.HACK, WeaponQuality.TRIP],
        description: "Derived from a farming tool the bill features a hooked blade that can be used to snag foes or chop them down."
    },
    HALBERD: {
        name: "Halberd",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.HACK, WeaponQuality.IMPALE],
        description: "The archetypal weapon of the forces of the Empire, the halberd can be employed to similar effect as either a spear or an axe."
    },
    MANCATCHER: {
        name: "Mancatcher",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.ENTANGLE],
        description: "The mancatcher is a strange polearm with a semi-circular head festooned with short spikes. The weapon may catch a person around the neck, forcing them to cease struggling for fear of further injury. The wielder benefits from a bonus of +20 to any Strength Tests made to entangle someone with the weapon."
    },
    PARTIZAN: {
        name: "Partizan",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.IMPALE, WeaponQuality.SLASH_2], // TODO Impale OR Slash
        description: "Partizans are spears with thick leafshaped blades, sacrificing some of the reach of the spear to inflict heavier cutting blows."
    },
    POLLAXE: {
        name: "Pollaxe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.HACK, WeaponQuality.IMPALE, WeaponQuality.PUMMEL], // TODO Hack OR Impale OR Pummel
        description: "The pollaxe takes many forms, but the archetypal design features a head with a short spike on the top for thrusting, an axe head to one side for cutting, and a hammer head on the other side for pummelling."
    },
    SPEAR: {
        name: "Spear",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 180,
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.IMPALE],
        description: "Besides the club, the spear is probably the most ubiquitous weapon in the Old World. Almost all species and nations employ troops armed with spears, aside from the Dwarfs who tend to eschew polearms in general."
    },
    PIKE: {
        name: "Pike",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 216,
        enc: 4,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.IMPALE],
        description: "These very long heavy spears are not commonly employed outside of specially trained regiments. Tilean mercenaries are particularly famed for their mastery of pikes and pike formations."
    },
    QUARTERSTAFF: {
        name: "Quarterstaff",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_STAFF,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 36,
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.PUMMEL],
        description: "Quarterstaffs are straight lengths of wood about as tall as their wielder. They are as often found as they are crafted."
    },
    ENCHANTED_STAFF: {
        name: "Enchanted Staff",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_STAFF,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 3600,
        enc: 2,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.PUMMEL],
        description: "Wizards typically bear staffs. They are badges of a Wizard's office as well as magical tools. A Wizard's staff is typically designed and decorated in a manner that attracts the Winds of Magic the Wizard works with. Staffs work by attracting the Winds with which they are associated. If a spellcaster bears a staff made to attract a Wind of Magic, spells from the corresponding Lore have their CN reduced by 1 (to a minimum of 0)."
    },
    BASTARD_SWORD: {
        name: "Bastard Sword",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SWORD,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 1920,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.DEFENSIVE],
        description: "Also known as a hand-and-a-half sword, the bastard sword is longer and heavier than a typical blade, but shorter and lighter than a zweihander. A fighter with Melee (Basic) could use a bastard sword as a singlehanded weapon, but it gains the Tiring and Slow Flaws."
    },
    GREAT_AXE: {
        name: "Great Axe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 960,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: [WeaponQuality.HACK, WeaponQuality.IMPACT, WeaponQuality.TIRING],
        description: "Rarely used by the Empire, but often employed by Norse tribes as a counter to heavy armour."
    },
    FLAMBERGE_ZWEIHANDER: {
        name: "Flamberge Zweihander",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SWORD,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 7200,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.HACK, WeaponQuality.SLASH_2],
        description: "The Empire's famous greatsword regiments are armed with massive steel blades, as long as many polearms. Certain master armourers go to even greater lengths in adding waves and serrated edges to their swords. These weapons are known as flamberge blades, and the wounds they inflict can be deeper as a result of their cutting power."
    },
    PICK: {
        name: "Pick",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 108,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.IMPALE, WeaponQuality.SLOW],
        description: "Two-handed military picks are rarely seen, their use being superseded by various forms of polearm. Certain subterranean species are known to employ them."
    },
    WARHAMMER_TH: {
        name: "Warhammer",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 720,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 6,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.PUMMEL, WeaponQuality.SLOW],
        description: "The two-handed warhammer is a difficult weapon to master, but it is associated with the Dwarfs and the Sigmarite cult."
    },
    ZWEIHANDER: {
        name: "Zweihander",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SWORD,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 2400,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.HACK],
        description: "The Empire's famous greatsword regiments are armed with massive steel blades, as long as many polearms. Certain master armourers go to even greater lengths in adding waves and serrated edges to their swords."
    }
};
// #endregion === WEAPONS MELEE SET === //
// === //
// #region ====== WEAPONS RANGED SET === //
TEW.DATABASE.WEAPONS.RANGED_SET = {
    ELF_BOW: {
        name: "Elf Bow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        twoHanded: true,
        price: 2400,
        enc: 2,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 150,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.PRECISE],
        description: "A bow made with the finests materials by the finests elven hands on Ulthuan."
    },
    LONGBOW: {
        name: "Longbow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        twoHanded: true,
        price: 1200,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 100,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DAMAGING],
        description: "A bow often used by bretonnian archers for better range."
    },
    BOW: {
        name: "Bow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        twoHanded: true,
        price: 960,
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 50,
        strBonus: true,
        damage: 3,
        qualities: [],
        description: "A classic bow to shoot arrows."
    },
    SHORTBOW: {
        name: "Shortbow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        twoHanded: true,
        price: 720,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 20,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "A lighter bow but with limited range and damage."
    },
    CROSSBOW_PISTOL: {
        name: "Crossbow Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CROSSBOW,
        group: WeaponGroup.CROSSBOW,
        groupLabel: WeaponGroupLabel.CROSSBOW,
        twoHanded: false,
        price: 1440,
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 10,
        strBonus: false,
        damage: 7,
        qualities: [WeaponQuality.PISTOL],
        description: "A small crossbow whitch can be used in close combat and has no need to reload."
    },
    HEAVY_CROSSBOW: {
        name: "Heavy Crossbow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CROSSBOW,
        group: WeaponGroup.CROSSBOW,
        groupLabel: WeaponGroupLabel.CROSSBOW,
        twoHanded: true,
        price: 1680,
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 100,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.RELOAD_2],
        description: "A heavy crossbow, hard to reload but devastating."
    },
    CROSSBOW: {
        name: "Crossbow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CROSSBOW,
        group: WeaponGroup.CROSSBOW,
        groupLabel: WeaponGroupLabel.CROSSBOW,
        twoHanded: true,
        price: 1200,
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 60,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.RELOAD_1],
        description: "A classic crossbow to shoot bolts."
    },
    LASSO: {
        name: "Lasso",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_WHIP,
        group: WeaponGroup.ENTANGLING,
        groupLabel: WeaponGroupLabel.ENTANGLING,
        twoHanded: false,
        price: 72,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 6,
        strBonus: false,
        damage: 0,
        qualities: [WeaponQuality.ENTANGLE],
        description: "A rope with a sliding knot, often used to catch livestock."
    },
    WHIP: {
        name: "Whip",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_WHIP,
        group: WeaponGroup.ENTANGLING,
        groupLabel: WeaponGroupLabel.ENTANGLING,
        twoHanded: false,
        price: 60,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 6,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.ENTANGLE],
        description: "A whip, often used by tamers."
    },
    SLING: {
        name: WeaponGroupLabel.SLING,
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        twoHanded: false,
        price: 12,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 60,
        strBonus: false,
        damage: 6,
        qualities: [],
        description: "A Halfing's favorite weapon, after the saucage pick of course."
    },
    STAFF_SLING: {
        name: "Staff Sling",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        twoHanded: true,
        price: 48,
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 100,
        strBonus: false,
        damage: 7,
        qualities: [],
        description: "empty"
    },
    BOLAS: {
        name: "Bolas",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CHAINS,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 12,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 9,
        strBonus: true,
        damage: 0,
        qualities: [WeaponQuality.ENTANGLE],
        description: "A weighted rope used to entangle people from a distance."
    },
    DART: {
        name: "Dart",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 24,
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 6,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.IMPALE],
        description: "A dart, mostly used in tavern games."
    },
    JAVELIN: {
        name: "Javelin",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 126,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 9,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.IMPALE],
        description: "A weapon whitch could be used for sports."
    },
    ROCK: {
        name: "Rock",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 0,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 9,
        strBonus: true,
        damage: 0,
        qualities: [],
        description: "Just a pebble really."
    },
    THROWING_AXE: {
        name: "Throwing Axe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 240,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 6,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.HACK],
        description: "An axe balanced to be thrown rather than being used in close combat."
    },
    THROWING_KNIFE: {
        name: "Throwing Knife",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 216,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 6,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "That is not made to cut meat but more to thrw to an opponent."
    },
    BOMB: {
        name: "Bomb",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOMB,
        group: WeaponGroup.EXPLOSIVES,
        groupLabel: WeaponGroupLabel.EXPLOSIVES,
        twoHanded: false,
        price: 720,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 3,
        strBonus: false,
        damage: 12,
        qualities: [WeaponQuality.BLAST_5, WeaponQuality.DANGEROUS, WeaponQuality.IMPACT],
        description: "Goes BOOM !"
    },
    INCENDIARY: {
        name: "Incendiary",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOMB,
        group: WeaponGroup.EXPLOSIVES,
        groupLabel: WeaponGroupLabel.EXPLOSIVES,
        twoHanded: false,
        price: 240,
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 3,
        strBonus: false,
        damage: 0, // TODO
        qualities: [WeaponQuality.BLAST_4, WeaponQuality.DANGEROUS],
        description: "A throwing bomb that sprays fire."
    },
    BLUNDERBUSS: {
        name: "Blunderbuss",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHOTGUN,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 480,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 20,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_2],
        description: "An early form of firearm, the Blunderbuss features a wide bore that exchanges accuracy for ease of operation. It is typically loaded with powder, wadding, and many small projectiles to improve the chance of scoring a hit. It may be loaded with either Small Shot and Powder or Scrap and Powder."
    },
    HOCHLAND_LONG_RIFLE: {
        name: "Hochland Long Rifle",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_RIFLE,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 24000,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 100,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.ACCURATE, WeaponQuality.PRECISE, WeaponQuality.RELOAD_4],
        description: "One of the legendary and incredibly precise weapons used by the hunters of Hochland, such rifles are incredibly prized. Often used to target enemy officers, such weapons are considered unsporting by many nobles and enemy soldiers caught with when them are summarily hanged."
    },
    HANDGUN: {
        name: "Handgun",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 960,
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 50,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_3],
        description: "A simple two-handed firearm, typically using a wheellock or flintlock design. Thousands of these are employed by the Empire state troops."
    },
    PISTOL: {
        name: "Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: false,
        price: 1920,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 20,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.PISTOL, WeaponQuality.RELOAD_1],
        description: "A smaller blackpowder weapon designed to be fired with one hand, these are often used in duels or by cavalry soldiers such as Outriders who require one hand to hold the reins of their mount. Wealthy individuals sometimes carry a brace pistols in lieue of reloading."
    },
    MATCHLOCK_HANDGUN: {
        name: "Matchlock Handgun",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 480,
        enc: 2,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 50,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_4],
        description: "An earlier design of handgun, a few of these relics persist around the Empire, and can often be had quite cheaply. Before use, a user must spend one action to light the fuse on their weapon. A lit fuse will burn for quite a while unless doused by rain or wind."
    },
    MATCHLOCK_BLUNDERBUSS: {
        name: "Matchlock Blunderbuss",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHOTGUN,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 240,
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 20,
        strBonus: false,
        damage: 7,
        qualities: [WeaponQuality.SPREAD_3, WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_3],
        description: "An earlier design of Blunderbuss, this weapon has the same drawbacks as the Matchlock Handgun, above."
    },
    ARQUEBUS: {
        name: "Arquebus",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_RIFLE,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 1200,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 40,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_5],
        description: "Little more than a scaled down cannon, the Arquebus is an ancient design indeed, often eschewing such innovations as sights, a trigger, or even a handle or grip. While early examples fired shot similar to or smaller than that used in modern blackpowder weapons, those surviving into current use in the Empire are typically larger bore weapons kept by nobles seeking to impress visitors. However, the sheer size of these relics renders them useful when the calibre of newer designs leaves something to be desired."
    },
    DOUBLE_BARRELLED_HANDGUN: {
        name: "Double-Barrelled Handgun",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 1680,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 50,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.REPEATER, WeaponQuality.RELOAD_4],
        description: "If one barrel is good, surely two is better? About as complex as a firearm can be while still being used by the common soldier, a double-barrelled handgun has two barrels and two triggers. Though heavy, most come with a device for reloading both barrels at once, allowing the user to fire more frequently."
    },
    GRIFFONSFOOT_PISTOL: {
        name: "Griffonsfoot Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: false,
        price: 2400,
        enc: 1,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 10,
        strBonus: false,
        damage: 7,
        qualities: [WeaponQuality.IMPRECISE, WeaponQuality.SPREAD_5, WeaponQuality.RELOAD_6],
        description: "This weapon is best employed against a tight group of enemies. A single trigger discharges all six barrels, and reloading requires six shots and commensurate amount of powder."
    },
    GUN_AXE: {
        name: "GunAxe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 1920,
        enc: 1,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 30,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_4],
        description: "This weapon is much as one might imagine - a handgun combined with an axe. It may be used as either a Hand Weapon or a Handgun. However, if used as an axe while loaded, any critical fumble will discharge the weapon into the torso of the user."
    },
    GUN_HALBERD: {
        name: "Gun Halberd",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 2400,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 30,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_4],
        description: "Employing the same principles as the Gun Axe, this weapon functions both as a halberd and as a handgun, with the firearm's barrel built into the haft of the Halberd. If used as a halberd while loaded, any critical fumble will discharge the weapon into anyone unlucky enough to be standing directly behind the user."
    },
    REPEATER_HANDGUN: {
        name: "Repeater Handgun",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.ENGINEERING,
        groupLabel: WeaponGroupLabel.ENGINEERING,
        twoHanded: true,
        price: 2400,
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 30,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_5, WeaponQuality.REPEATER_4],
        description: "A Repeater Handgun uses a cunning method, often involving clockwork or other intricate mechanisms, to place fresh ammunition into a position to fire each time the weapon is discharged. Rarely are two such weapons identical, though rotating mechanisms are a common feature."
    },
    REPEATER_PISTOL: {
        name: "Repeater Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.ENGINEERING,
        groupLabel: WeaponGroupLabel.ENGINEERING,
        twoHanded: false,
        price: 3600,
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 10,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.PISTOL, WeaponQuality.RELOAD_4, WeaponQuality.REPEATER_4],
        description: "Even more challenging to create than a Repeater Handgun due to their smaller size, RepeaterPistols otherwise share much in common with their larger cousins. Clockwork mechanisms are common, as are rotating chambers filled with ammunition. Minute adjustments are required constantly, and in the hands of an untrained user such weapons often misfire spectacularly."
    },
    HAND_MORTAR: {
        name: "Hand Mortar",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.ENGINEERING,
        groupLabel: WeaponGroupLabel.ENGINEERING,
        twoHanded: true,
        price: 12000,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 30,
        strBonus: false,
        damage: 7,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_2],
        description: "Looking like a short, squat Blunderbuss, the Hand Mortar is a scaled down mortar designed to lob bombs and other large items in a desired direction. It is quite dangerous to use, as loading a little too much powder, or mistiming the fuse on a loaded bomb, will see the weapon explode quite spectacularly. Any fumble while reloading the weapon causes it to explode. However, the device does open up many opportunities for those willing to risk its use."
    },
    CANE_PISTOL: {
        name: "Cane Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.ENGINEERING,
        groupLabel: WeaponGroupLabel.ENGINEERING,
        twoHanded: false,
        price: 3600,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 10,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_6],
        description: "A small-bore pistol concealed in a walking stick or cane, this weapon is somewhat impractical, but very hard to spot."
    }
};
// #endregion === WEAPONS RANGED SET === //
// === //
// #region ====== WEAPONS AMMO SET === //
TEW.DATABASE.WEAPONS.AMMO_SET = {
    ARROW: {
        name: "Arrow",
        groupIcon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 12,
        price: 60,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.IMPALE],
        description: "A classic arrow to use with a bow."
    },
    BARBED_ARROW: {
        name: "Barbed Arrow",
        groupIcon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 12,
        price: 96,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.SLASH_1],
        description: "A sharp arrow designed to remain in the flesh of the target."
    },
    BODKIN_ARROW: {
        name: "Bodkin Arrow",
        groupIcon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 12,
        price: 96,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "A square-based arrow, used to penetrate heavy armor."
    },
    ELF_ARROW: {
        name: "Elf Arrow",
        groupIcon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 1,
        price: 72,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: "+50",
        damage: "+1",
        qualities: [WeaponQuality.ACCURATE, WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "A perfectly balanced an sharpened arrow, designed by the High Elves."
    },
    SHARP_STICK: {
        name: "Sharp Stick",
        groupIcon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 1,
        price: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "/2",
        damage: "-2",
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.UNDAMAGING],
        description: "Just a pointy stick."
    },
    BOLT: {
        name: "Bolt",
        groupIcon: TEW.DATABASE.ICONS.SET.WEAPON_CROSSBOW,
        group: WeaponGroup.CROSSBOW,
        groupLabel: WeaponGroupLabel.CROSSBOW,
        ammountSold: 12,
        price: 60,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.IMPALE],
        description: "A simple bolt to use with a crossbow."
    },
    LEAD_BULLET: {
        name: "Lead Bullet",
        groupIcon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        ammountSold: 12,
        price: 4,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "-10",
        damage: "+1",
        qualities: [WeaponQuality.PUMMEL],
        description: "A bullet made of lead to throw with a sling."
    },
    PEBBLE: {
        name: "Pebble",
        groupIcon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        ammountSold: 1,
        price: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "-10",
        damage: "-2",
        qualities: [WeaponQuality.IMPRECISE, WeaponQuality.UNDAMAGING],
        description: "A simple pebble picked up from the ground."
    },
    STONE_BULLET: {
        name: "Stone Bullet",
        groupIcon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        ammountSold: 12,
        price: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.PUMMEL],
        description: "A projectile made of stone to be throwned by a sling."
    },
    BULLET_AND_POWDER: {
        name: "Bullet and Powder",
        groupIcon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 39,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+1",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "Fired from most Pistols, Handguns and their variants, bullets come in a small oiled sack and are typically sold with enough powder to fire them under normal circumstances."
    },
    PAPER_CARTRIDGE: { //TODO
        name: "Paper Cartridge",
        groupIcon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 60,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+1",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING, WeaponQuality.FASTER_RELOAD],
        description: "These are pre prepared packages of shot, powder, and wadding, making reloading blackpowder weapons far easier. Tests made to reload a suitable weapon with this ammunition benefit from a +10 bonus."
    },
    AQSHY_INFUSED_POWDER: { //TODO
        name: "Aqshy-Infused Powder",
        groupIcon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 240,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: "+10",
        damage: "+2",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "For the very brave or foolish, this powder is created from sand from the Nehekeran desert, infused with additional Aqshy by means known only to the Bright College in Altdorf. It is more explosive than normal powder but does wear down barrels far more quickly than its mundane counterpart. Any failed Test that includes either an 8 or 9 on either the 10s or units die counts as a Fumble when using this powder."
    },
    PRECISION_SHOT_AND_POWDER: {
        name: "Precision Shot and Powder",
        groupIcon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 1,
        price: 36,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+1",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING, WeaponQuality.PRECISE],
        description: "Expertly prepared powder and carefully smoothed and rounded bullets can be combined to allow for more reliable, precise shots with any suitable Blackpowder weapon."
    },
    IMPROVISED_SHOT_AND_POWDER: {
        name: "Improvised Shot and Powder",
        groupIcon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 1,
        price: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "/2",
        damage: "+0",
        qualities: [],
        description: "A smidge of powder, possibly damp, and whatever stone looks like it might fit down the barrel of a gun."
    },
    SMALL_SHOT_AND_POWDER: {
        name: "Small Shot and Powder",
        groupIcon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 39,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.SPREAD_3],
        description: "Often used for hunting birds and other small, fast moving creatures, Small Shot is far smaller than the barrels of most weapons, and the user is expected to use a dozen or so for each load."
    },
    SCRAP_AND_POWDER: {
        name: "Scrap and Powder",
        groupIcon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 24,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "/2",
        damage: "-1",
        qualities: [WeaponQuality.SPREAD_3, WeaponQuality.INFECTED],
        description: "Scrap is a catch-all term for old roofing nails, used horseshoe fragments, arrow heads, and other bits of sharp and pointy material scavenged from whatever pile or rust or slag can be found. Attacks made using this shot benefit from the Infected Creature Trait."
    },
    LARGE_BULLET_AND_POWDER: {
        name: "Large Bullet and Powder",
        groupIcon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 240,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+2",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.IMPACT, WeaponQuality.PENETRATING],
        description: "Technically a small cannonball, these shots are loaded into large bore weapons such as an Arquebus or Hand Mortar. Those firing such a device, or standing within 2 yards of the user, must make a Challenging (+0) Endurance Test or gain a Deafened Condition."
    }
};
// #endregion === WEAPONS AMMO SET === //
// === //
// #region ====== WEAPONS IDS === //
// The IDs are the keys of the SET objects MELE_SET, RANGED_SET
TEW.DATABASE.WEAPONS.IDS = Object.keys(TEW.DATABASE.WEAPONS.MELEE_SET)
        .concat(Object.keys(TEW.DATABASE.WEAPONS.RANGED_SET))
        .sort((a, b) => a.localeCompare(b));
// Those are the IDs of the groups
TEW.DATABASE.WEAPONS.GROUP_IDS = [
    "BASIC",
    "CAVALRY",
    "FENCING",
    "BRAWLING",
    "FLAIL",
    "PARRY",
    "POLE_ARM",
    "TWO_HANDED",
    "BOW",
    "CROSSBOW",
    "ENTANGLING",
    "SLING",
    "THROWING",
    "EXPLOSIVES",
    "BLACKPOWDER",
    "ENGINEERING"
];
// #endregion === WEAPONS IDS === //
// === //
// #region ====== WEAPONS ARRAY === //
// This is a 2D array, where the first element is the key and the second element is the value
TEW.DATABASE.WEAPONS.ARRAY = TEW.DATABASE.WEAPONS.IDS
        .map((key: string) => [key, TEW.DATABASE.WEAPONS.MELEE_SET[key] || TEW.DATABASE.WEAPONS.RANGED_SET[key]])
// #endregion === WEAPONS ARRAY === //

TEW.DATABASE.WEAPONS.AMMO_IDS = Object.keys(TEW.DATABASE.WEAPONS.AMMO_SET).sort((a, b) => a.localeCompare(b));
TEW.DATABASE.WEAPONS.AMMO_ARRAY = TEW.DATABASE.WEAPONS.AMMO_IDS.map((key: string) => [key, TEW.DATABASE.WEAPONS.AMMO_SET[key]]);
