// $PluginCompiler TEW_Constants.js
import TEW from "../types/enum";
import { Availability, ItemGroup, ItemGroupLabel } from "../types/enum";
import { Item } from "../types/item";

// $StartCompilation
TEW.ITEMS = {
    AMULET: {
        name: "Amulet",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/0/2",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "A brass amulent representing Sigmar."
    },
    BOOTS: {
        name: "Boots",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/5/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Sturdy boots to keep your feet dry."
    },
    CLOTHING: {
        name: "Clothing",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/6/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Common clothes."
    },
    COAT: {
        name: "Coat",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/18/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Protects you against the elements."
    },
    COSTUME: {
        name: "Costume",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "1/0/0",
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Expensive clothes to shine in society."
    },
    COURTLY_GARB: {
        name: "Courtly Garb",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "12/0/0",
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Nobles’ garb features embellishments such as lace cuffs & collars, excessive high-quality fabric and pointed shoes."
    },
    FACE_POWDER: {
        name: "Face Powder",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/10/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Stylish makeup for the noblefolk."
    },
    GLOVES: {
        name: "Gloves",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/4/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "To keep your hands dry and warm."
    },
    HAT: {
        name: "Hat",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/4/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Fine quality hats are status symbols in the Empire's towns and cities. The more flamboyant the hat, the better."
    },
    HOOD: {
        name: "Hood",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/5/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Usefull to keep your head dry, or to hide it."
    },
    JEWELLERY: {
        name: "Jewellery",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "8/0/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Nice jewels with various gemstones."
    },
    PERFUME: {
        name: "Perfume",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/10/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Smells nicer than most people."
    },
    PINS: {
        name: "Pins",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 6,
        price: "0/10/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Small silver pins."
    },
    RELIGIOUS_SYMBOL: {
        name: "Religious Symbol",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/6/8",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Small silver symbol representing a god."
    },
    ROBES_PRACTICAL: {
        name: "Practical Robes",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "1/0/0",
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "These costumes are inexpensive, comfortable, and relatively plain. A wizard wearing practical robes may even go unrecognised in many situations. Gives +1 SL to any Channeling test."
    },
    ROBES_STANDARD: {
        name: "Standard Robes",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "8/0/0",
        enc: 2,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "These costumes are complex and typically include heavy coats or cloaks and distinctive headwear. Gives +2 SL to any Channeling test."
    },
    ROBES_ELABORATE: {
        name: "Elaborate Robes",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "30/0/0",
        enc: 4,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "These costumes are heavy and impractical, often incorporating bulky accessories and reams of cloth woven from magically infused thread. Anyone wearing these robes will be instantly recognised as a wizard. Gives +3 SL to any Channeling test."
    },
    SCEPTRE: {
        name: "Sceptre",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "8/0/0",
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "The highest-ranking legal officials carry sceptres to indicate their status."
    },
    SHOES: {
        name: "Shoes",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/5/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Nice shoes to keep your feet dry."
    },
    SIGNET_RING: {
        name: "Signet Ring",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "5/0/0",
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "Gold ring with engraved stamp."
    },
    TATOO: {
        name: "Tatoo",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "0/4/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Definitive mark made with totally clean tools."
    },
    UNIFORM: {
        name: "Uniform",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "1/2/0",
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Outfit with the city's coat of arms."
    },
    WALKING_CANE: {
        name: "Walking Cane",
        group: ItemGroup.CLOTHES,
        groupIcon: TEW.ICONS_IDS.ITEM_CLOTHES,
        groupLabel: ItemGroupLabel.CLOTHES,
        nb: 1,
        price: "3/0/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Polished wooden canes with metal caps are status symbols amongst wealthier townsfolk."
    },
    ALE_PINT: {
        name: "Ale, pint",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/0/3",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Pint of the finest ale you can find, not really good though."
    },
    ALE_KEG: {
        name: "Ale, keg",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/3/0",
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Keg full of the finest ale you can find, not really good though."
    },
    BUGMANS_ALE_PINT: {
        name: "Bugman's XXXXXX Ale, pint",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/0/9",
        enc: 0,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "Merchants travel across the Old World to purchase this potent Dwarfen ale from the famous brewery founded by Josef Bugman."
    },
    FOOD_ONE_DAY: {
        name: "Food, Groceries/day",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/0/10",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Enough food to feed one person for one day. Needs to be prepared."
    },
    MEAL_INN: {
        name: "Meal, inn",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/1/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Hot meal served in a wooden plate."
    },
    RATIONS_ONE_DAY: {
        name: "Rations, one day",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/2/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Food to go for one person for one day."
    },
    ROOM_COMMON: {
        name: "Common Room/night",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/0/10",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "One night in the common room for one person. Guests sleeping in common rooms should be wary of thieves."
    },
    ROOM_PRIVATE: {
        name: "Private Room/night",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/10/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "One night in a private room. Accommodates 2 guests."
    },
    SPIRITS_PINT: {
        name: "Spirits, pint",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/2/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "One pint of fine spirits."
    },
    STABLES_NIGHT: {
        name: "Stables/night",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/0/10",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Room for one horse in the stables fon one night."
    },
    WINE_BOTTLE: {
        name: "Wine Bottle",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/0/10",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "A bottle of fine wine."
    },
    WINE_GLASS: {
        name: "Wine Glass",
        group: ItemGroup.FOOD,
        groupIcon: TEW.ICONS_IDS.ITEM_FOOD,
        groupLabel: ItemGroupLabel.FOOD,
        nb: 1,
        price: "0/0/4",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "A glass of fine wine."
    },
    ABACUS: {
        name: "Abacus",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/3/4",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Mechanical tool facilitating calculus."
    },
    ANIMAL_TRAP: {
        name: "Animal Trap",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/2/6",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Used to catch animals like wolves or rabbits."
    },
    ANTITOXIN_KIT: {
        name: "Antitoxin Kit",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "3/0/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Contains a small knife, herbs, and a jar of leeches. A successful Heal Test with an antitoxin kit removes all Poisoned Conditions. Treatment takes at least two Rounds."
    },
    BOAT_HOOK: {
        name: "Boat Hook",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/5/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Tool used to catch boats from shore."
    },
    BROOM: {
        name: "Broom",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/0/10",
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "It's a broom, nothing more."
    },
    BUCKET: {
        name: "Bucket",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/2/6",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Can be used to move liquids."
    },
    CHISEL: {
        name: "Chisel",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/4/2",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Little tool used to scult stone."
    },
    COMB: {
        name: "Comb",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/0/10",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Used to brush your hair."
    },
    CROWBAR: {
        name: "Crowbar",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/2/6",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Metal bar that can be used as an improvised weapon."
    },
    CRUTCH: {
        name: "Crutch",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/3/0",
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Helps you walk."
    },
    DISGUISE_KIT: {
        name: "Disguise Kit",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/6/6",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Contains enough props for four disguises and also materials for changing your appearance used by those with the Entertain (Acting) Skill."
    },
    EAR_PICK: {
        name: "Ear Pick",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/2/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "To clean your ears."
    },
    FISH_HOOKS: {
        name: "Fish Hooks",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 12,
        price: "0/1/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Can be used to catch fish."
    },
    FLOOR_BRUSH: {
        name: "Floor Brush",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/1/6",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Little brush, often used in rich houses."
    },
    GAVEL: {
        name: "Gavel",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "1/0/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Little hammer used by judges and magistrates."
    },
    HAMMER: {
        name: "Hammer",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/3/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Tool used to punch nails."
    },
    HAND_MIRROR: {
        name: "Hand Mirror",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "1/1/6",
        enc: 0,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "Little mirror used by nobles."
    },
    HOE: {
        name: "Hoe",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/4/0",
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Farming tool."
    },
    KEY: {
        name: "Key",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/1/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "No idea what it opens."
    },
    LOCK_PICK: {
        name: "Lock Pick",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/15/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "An assortment of small, variously-shaped tools needed to use the Pick Lock Skill without penalty."
    },
    MANACLES: {
        name: "Manacles",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/18/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Prisoners trying to break out of manacles suffer 1 Wound and must pass a Very Hard (-30) Strength Test."
    },
    MOP: {
        name: "Mop",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/1/0",
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Used to clean the floor."
    },
    NAILS: {
        name: "Nails",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 12,
        price: "0/0/2",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Cna be punched by a hammer."
    },
    PAINT_BRUSH: {
        name: "Paint Brush",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/4/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Brush used by artists to paint on canvas."
    },
    PESTLE_AND_MORTAR: {
        name: "Pestle and Mortar",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/14/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Tools used by an apothecary."
    },
    PICK: {
        name: "Pick",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/18/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Tool used by minors."
    },
    POLE: {
        name: "Pole (3 yards)",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/8/0",
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "A long pole used for barging; counts as an Improvised Weapon."
    },
    QUILL_PEN: {
        name: "Quill Pen",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/3/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Expensive writing tool."
    },
    RAKE: {
        name: "Rake",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/4/6",
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Usefull to removes leaves from your garden."
    },
    READING_LENS: {
        name: "Reading Lens",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "3/0/0",
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "Glass lenses with handles provide a +20 bonus to Read/Write Tests for deciphering tiny or unintelligible writing. Perception Tests to search for fine details such as secret doors or compartments also receive a +20 bonus."
    },
    SAW: {
        name: "Saw",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/6/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Tool used to cut wood."
    },
    SICKLE: {
        name: "Sickle",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "1/0/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Tool used by herborists to collect herbs."
    },
    SPADE: {
        name: "Spade",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/8/0",
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Farming tool."
    },
    SPIKE: {
        name: "Spike",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/1/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Great spike."
    },
    STAMP: {
        name: "Stamp, engraved",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "5/0/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Stamp engraved with heraldry."
    },
    TONGS: {
        name: "Tongs, steel",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/16/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Usefull to spread laundry."
    },
    TELESCOPE: {
        name: "Telescope",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "5/0/0",
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "Tool used to watch the stars."
    },
    TWEEZERS: {
        name: "Tweezers",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "0/1/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Usefull."
    },
    WRITING_KIT: {
        name: "Writing Kit",
        group: ItemGroup.TOOLS,
        groupIcon: TEW.ICONS_IDS.ITEM_TOOLS,
        groupLabel: ItemGroupLabel.TOOLS,
        nb: 1,
        price: "2/0/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Contains a quill pen, inkpot, and ink blotter."
    },
    APOTHECARY_BOOK: {
        name: "Apothecary Book",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "8/0/0",
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Apothecary books are usually hand-written. A basic apothecary book contains ingredient descriptions and diagrammed instructions for brewing processes. Formulas for Digestive Tonics, Healing Draughts, and Vitality Draughts are usually included. Advanced texts contain formulas for more exotic draughts."
    },
    ART_BOOK: {
        name: "Art Book",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "5/0/0",
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "Plays, poems, and ballads or perhaps musical arrangements scribbled on loose parchment, Art books come inmany forms. They also include treatises on perspective, form, and style, often written by famous painters or sculptors — such as Leonardo da Miragliano — for mass printing."
    },
    CRYPTOGRAPHY_BOOK: {
        name: "Cryptography Book",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "8/0/0",
        enc: 1,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "Where individual ciphers and encryption keys can be written on a single page or two, Cryptography books are often hand-scribed codices dealing with mathematics, numerology, and polyalphabetic encryption."
    },
    ENGINEER_BOOK: {
        name: "Engineer Book",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "3/0/0",
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "The majority of engineering books are pressprinted. Engineering is an advanced science in the Empire, largely due to the Imperial Engineers’ School in Altdorf and the Dwarf Engineers’ Guild. Because of this, Engineering texts are often authored, co-authored, or edited by Dwarfs."
    },
    LAW_BOOK: {
        name: "Law Book",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "15/0/0",
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "Laws vary considerably from one region to the next. Cities with printing presses compile legislation in bound volumes, whereas judges in smaller towns often rely on documents handwritten centuries ago. Law books used by travelling lawyers or judges often combine printed and written pages from different towns across the Empire, collated and bound together within the same cover."
    },
    MAGIC_GRIMOIRE: {
        name: "Magic Grimoire",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "20/0/0",
        enc: 1,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "Spell grimoires are usually scribed by wizards, and their covers are often secured with locks. Sometimes grimoires are even protected by magical alarms or wards. Carrying a spell grimoire is punishable as heresy unless the owning wizard is licensed by the Colleges of Magic."
    },
    MEDICINE_BOOK: {
        name: "Medicine Book",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "15/0/0",
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "Medical texts can either be scribed or pressprinted, depending on the authoring physician’s prestige. Illuminations are common, and usually include detailed autopsy drawings and procedural diagrams."
    },
    RELIGION_BOOK: {
        name: "Religion Book",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "1/0/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Religions books come in all forms in the Empire, a realm renowned for its religious observances. There is a eager market for the most popular texts, most of which are cheaply produced by printing presses."
    },
    GUILD_LICENSE: {
        name: "Guild License",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "0/0/0",
        enc: 0,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "Guild licenses are usually printed on single sheets of parchment, stamped with an official seal, and signed by the local guild master. Guild licenses are not purchased; instead, they are granted to guild members according to each guild’s traditions and laws."
    },
    LEAFLET: {
        name: "Leaflet",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "0/1/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "Leaflets contain usefull information about the local city and customs."
    },
    LEGAL_DOCUMENT: {
        name: "Legal Document",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "0/3/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "A simple legal document such as a will, IOU or letter of intent."
    },
    MAP: {
        name: "Map",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "3/0/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "A map of the surronding lands."
    },
    PARCHMENT: {
        name: "Parchment",
        group: ItemGroup.BOOKS,
        groupIcon: TEW.ICONS_IDS.ITEM_BOOKS,
        groupLabel: ItemGroupLabel.BOOKS,
        nb: 1,
        price: "0/1/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        description: "A piece of parchment."
    },
    BLACK_LOTUS: {
        name: "Black Lotus",
        group: ItemGroup.DRUGS,
        groupIcon: TEW.ICONS_IDS.ITEM_DRUGS,
        groupLabel: ItemGroupLabel.DRUGS,
        nb: 1,
        price: "20/0/0",
        enc: 0,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "This deadly plant grows in Southland jungles and is used for blade venom. Victims who suffer at least 1 Wound from a sap-coated blade immediately take 2 Poisoned Conditions. Resisted with a Difficult (–10) Endurance Test."
    },
    HEARTKILL: {
        name: "Heartkill",
        group: ItemGroup.DRUGS,
        groupIcon: TEW.ICONS_IDS.ITEM_DRUGS,
        groupLabel: ItemGroupLabel.DRUGS,
        nb: 1,
        price: "40/0/0",
        enc: 0,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "Combining the venoms from an Amphisbaena (a rare, two-headed serpent) and a Jabberslythe produces an odourless, colourless poison. When ingested, the deadly mixture inflicts 4 Poisoned Conditions. Resisted with a Difficult (–10) Endurance Test."
    },
    MAD_CAP_MUSHROOMS: {
        name: "Mad Cap Mushrooms",
        group: ItemGroup.DRUGS,
        groupIcon: TEW.ICONS_IDS.ITEM_DRUGS,
        groupLabel: ItemGroupLabel.DRUGS,
        nb: 1,
        price: "5/0/0",
        enc: 0,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        description: "These hallucinogenic mushrooms are eaten by Goblin fanatics before battle. They induce a berserker rage, adding +10 Strength, +4 Wounds, and the Frenzy Talent. When the effect wears off, the user loses 1d10 Wounds. Non- Greenskins must also pass a Challenging (+0) Endurance Test or contract a Minor Infection. Duration: Active when chewed plus an additional 2d10 minutes."
    },
    MANDRAKE_ROOT: {
        name: "Mandrake Root",
        group: ItemGroup.DRUGS,
        groupIcon: TEW.ICONS_IDS.ITEM_DRUGS,
        groupLabel: ItemGroupLabel.DRUGS,
        nb: 1,
        price: "1/0/0",
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "This highly-addictive deliriant grows under gallows, and is chewed to keep an unquiet mind still. Users must pass a Willpower Test every Round to perform an Action or a Move (choose one); further, Movement is halved. However, Cool Tests receive a bonus of +20. Duration: Active when chewed plus an additional 1d10×10 minutes."
    },
    MOONFLOWER: {
        name: "Moonflower",
        group: ItemGroup.DRUGS,
        groupIcon: TEW.ICONS_IDS.ITEM_DRUGS,
        groupLabel: ItemGroupLabel.DRUGS,
        nb: 1,
        price: "5/0/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "This tranquilliser is a dried moss which grows only on leaves in the Laurelorn forest. Elves use Moonflower to treat Black Plague, granting a bonus of +30 to any associated Tests for Elves to resist the disease, otherwise it has no effect on their species. Others can inhale vapours from boiling the moss and if they fail a Very Hard (–30) Willpower Test will gain an Unconscious Condition; if passed, they receive a bonus of +20 to Cool Tests and gain a Fatigued Condition. Moonflower is used by the most expensive Physicians as an anesthetic. Duration: 1d10+5 hours."
    },
    RANALDS_DELIGHT: {
        name: "Ranald's Delight",
        group: ItemGroup.DRUGS,
        groupIcon: TEW.ICONS_IDS.ITEM_DRUGS,
        groupLabel: ItemGroupLabel.DRUGS,
        nb: 1,
        price: "0/18/0",
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        description: "This highly-addictive stimulant is a synthetic compound made from sulphur, mercury and other elements. Inhaling the powder provides a bonus of +1 to Movement, and +10 to WS, S, T, and Agi. This last for 3 hours, after which the user suffers a penalty of –2 Movement and –20 on Weapon Skill, Strength, Toughness, and Agility. Duration: 1 day."
    },
    SPIT: {
        name: "Spit",
        group: ItemGroup.DRUGS,
        groupIcon: TEW.ICONS_IDS.ITEM_DRUGS,
        groupLabel: ItemGroupLabel.DRUGS,
        nb: 1,
        price: "1/5/0",
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "Extracted from Chameleoleeches found in the marshes of the Empire, this extraordinarily powerful hallucinogen brings visions of something deeply desired, such as a lost lover, a dead friend, or a missing child. Called Spit on the streets, it’s popular with those lost to despair. Upon exposure, you must pass a Very Hard (–30) Toughness Test or be lost to a fully real fantasy, which is a matter for the GM to handle. Duration: 1d10 minutes."
    },
    WEIRDROOT: {
        name: "Weirdroot",
        group: ItemGroup.DRUGS,
        groupIcon: TEW.ICONS_IDS.ITEM_DRUGS,
        groupLabel: ItemGroupLabel.DRUGS,
        nb: 1,
        price: "0/4/0",
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        description: "One of the most common street-drugs in the Empire, Weirdroot is chewed, bringing a sense of euphoria and pleasant hallucinations, which some suggest may be connected to the Winds of Magic. The drug gives a +10 bonus to Toughness and Willpower Tests, but a penalty of –10 to Agility, Initiative, and Intelligence Tests. Duration: Active when chewed plus an additional 1d10×10 minutes."
    }
} as Record<string, Item>;

TEW.ITEM_IDS = Object.keys(TEW.ITEMS).sort((a, b) => a.localeCompare(b));
TEW.ITEMS_ARRAY = Object.keys(TEW.ITEMS).map(item => [item, TEW.ITEMS[item]]);
