// $PluginCompiler TEW_Constants.js
// $StartCompilation
TEW.MELEE_WEAPONS = TEW.MELEE_WEAPONS || {
    AXE: {
        name: "Axe",
        icon: TEW.ICONS_IDS.WEAPON_AXE,
        group: "BASIC",
        groupLabel: "Basic",
        price: "0/10/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["HACK", "UNBALANCED"],
        description: "Much beloved of Dwarfs, the axe is not as agile in the hand as a sword but the heavy cleaving head can make a mess of armour and shields."
    },
    BALLOCK_KNIFE: {
        name: "Ballock Knife",
        icon: TEW.ICONS_IDS.WEAPON_KNIFE,
        group: "BASIC",
        groupLabel: "Basic",
        price: "0/16/0",
        enc: 0,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: ["IMPALE", "PENETRATING", "PRECISE"],
        description: "The short, slim blade of a ballock knife makes for a poor weapon, unless you have a heavily armoured opponent at your mercy."
    },
    CLUB: {
        name: "Club",
        icon: TEW.ICONS_IDS.WEAPON_MACE,
        group: "BASIC",
        groupLabel: "Basic",
        price: "0/4/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["UNDAMAGING", "UNBALANCED"],
        description: "Clubs are as often found as they are crafted."
    },
    DAGGER: {
        name: "Dagger",
        icon: TEW.ICONS_IDS.WEAPON_KNIFE,
        group: "BASIC",
        groupLabel: "Basic",
        price: "0/16/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "These blades are crafted specifically for fighting."
    },
    IMPROVISED_WEAPON: {
        name: "Improvised Weapon",
        icon: TEW.ICONS_IDS.WEAPON_PIPE,
        group: "BASIC",
        groupLabel: "Basic",
        price: "0/0/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: ["UNDAMAGING", "UNBALANCED"],
        description: "Hard and heavy items that are not intended to be used as a weapon may still serve in a desperate moment. This entry covers such items as chair legs, rocks, snooker cues, and bottles."
    },
    KNIFE: {
        name: "Knife",
        icon: TEW.ICONS_IDS.WEAPON_KNIFE,
        group: "BASIC",
        groupLabel: "Basic",
        price: "0/8/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: ["UNDAMAGING"],
        description: "This entry covers short, sharp blades intended for purposes other than fighting, such as kitchen or hunting knives."
    },
    MACE: {
        name: "Mace",
        icon: TEW.ICONS_IDS.WEAPON_MACE,
        group: "BASIC",
        groupLabel: "Basic",
        price: "0/15/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["PUMMEL", "UNBALANCED"],
        description: "The typical mace is a metal shaft with a heavy head shaped in flanges or spiked protrusions. Whilst it is less wieldy than a sword it inflicts concussive blows."
    },
    MILITARY_PICK: {
        name: "Military Pick",
        icon: TEW.ICONS_IDS.WEAPON_MACE,
        group: "BASIC",
        groupLabel: "Basic",
        price: "0/15/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["PENETRATING", "UNBALANCED"],
        description: "Crude picks are little more than a metal spike on the end of a stick, though better made weapons are fashioned from steel. They are not agile weapons but are well designed to crack armour."
    },
    SCIMITAR: {
        name: "Scimitar",
        icon: TEW.ICONS_IDS.WEAPON_SABER,
        group: "BASIC",
        groupLabel: "Basic",
        price: "1/0/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["SLASH_1"],
        description: "Popular in the east of the Empire, Kislev and Araby, the scimitar has a curved blade which can inflict terrible cutting wounds. Its design does compromise the welder’s ability to lunge and thrust, meaning that even though scimitars are a similar length to straight swords they have a shorter reach."
    },
    SWORD: {
        name: "Sword",
        icon: TEW.ICONS_IDS.WEAPON_SWORD,
        group: "BASIC",
        groupLabel: "Basic",
        price: "1/0/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [],
        description: "The sword is the weapon by which all others are measured. A quality sword has a needle point tip for thrusting, a blade that is razor sharp to either side, and is balanced so that the weight is close to the hand, making it agile for attack and defence."
    },
    WARHAMMER: {
        name: "Warhammer",
        icon: TEW.ICONS_IDS.WEAPON_MACE,
        group: "BASIC",
        groupLabel: "Basic",
        price: "1/0/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["PENETRATING", "PUMMEL", "UNBALANCED"],
        description: "Warhammers come in several designs, but typically have a flat heavy head on one side for inflicting pummelling damage, and a spiked point on the other for penetrating armour."
    },
    SHIELD_BUCKLER: {
        name: "Shield (Buckler)",
        icon: TEW.ICONS_IDS.WEAPON_SHIELD,
        group: "BASIC",
        groupLabel: "Basic",
        price: "0/18/2",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "Personnal",
        strBonus: true,
        damage: 1,
        qualities: ["SHIELD_1", "DEFENSIVE", "UNDAMAGING"],
        description: "A small shield to save you from harm."
    },
    SHIELD: {
        name: "Shield",
        icon: TEW.ICONS_IDS.WEAPON_SHIELD,
        group: "BASIC",
        groupLabel: "Basic",
        price: "2/0/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["SHIELD_2", "DEFENSIVE", "UNDAMAGING"],
        description: "A regular shield, ideal for close combat."
    },
    SHIELD_LARGE: {
        name: "Shield (Large)",
        icon: TEW.ICONS_IDS.WEAPON_SHIELD,
        group: "BASIC",
        groupLabel: "Basic",
        price: "3/0/0",
        enc: 3,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["SHIELD_3", "DEFENSIVE", "UNDAMAGING"],
        description: "A large shield to protect you from all enemies"
    },
    PAVISE: {
        name: "Pavise",
        icon: TEW.ICONS_IDS.WEAPON_SHIELD,
        group: "BASIC",
        groupLabel: "Basic",
        price: "3/15/0",
        enc: 4,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["SHIELD_5"],
        description: "The pavise is a large shield carried by crossbowmen to provide shelter on the battlefield as they reload. Roughly 4 feet tall and often painted with the unit’s coat of arms, the crossbowman plants the pavise on the ground like a personal wall."
    },
    CAVALRY_HAMMER: {
        name: "Cavalry Hammer",
        icon: TEW.ICONS_IDS.WEAPON_MACE,
        group: "CAVALRY",
        groupLabel: "Cavalry",
        price: "3/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["PUMMEL"],
        description: "Cavalry hammers are large, weighty weapons, favoured by the Knights of the White Wolf. On foot, they may be used with the Melee (Two-Handed) skill."
    },
    DEMI_LANCE: {
        name: "Demi-Lance",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "CAVALRY",
        groupLabel: "Cavalry",
        price: "1/0/0",
        enc: 2,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["IMPACT", "IMPALE"],
        description: "Lances resemble spears, but with a weighty grip designed to brace the weapon against the arm and chest of a charging knight. The demi-lance is similar, but shorter and lighter."
    },
    LANCE: {
        name: "Lance",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "CAVALRY",
        groupLabel: "Cavalry",
        price: "1/0/0",
        enc: 3,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: ["IMPACT", "IMPALE"],
        description: "Lances resemble spears, but with a weighty grip designed to brace the weapon against the arm and chest of a charging knight. The demi-lance is similar, but shorter and lighter."
    },
    SABRE: {
        name: "Sabre",
        icon: TEW.ICONS_IDS.WEAPON_SABER,
        group: "CAVALRY",
        groupLabel: "Cavalry",
        price: "0/10/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["SLASH_1"],
        description: "empty"
    },
    FOIL: {
        name: "Foil",
        icon: TEW.ICONS_IDS.WEAPON_FOIL,
        group: "FENCING",
        groupLabel: "Fencing",
        price: "5/0/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["FAST", "IMPALE", "PRECISE", "UNDAMAGING"],
        description: "empty"
    },
    RAPIER: {
        name: "Rapier",
        icon: TEW.ICONS_IDS.WEAPON_RAPIER,
        group: "FENCING",
        groupLabel: "Fencing",
        price: "5/0/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["FAST", "IMPALE"],
        description: "empty"
    },
    SMALLSWORD: {
        name: "Smallsword",
        icon: TEW.ICONS_IDS.WEAPON_FOIL,
        group: "FENCING",
        groupLabel: "Fencing",
        price: "4/0/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["FAST", "IMPALE", "PRECISE"],
        description: "empty"
    },
    SPIKED_GAUNTLET: {
        name: "Spiked Gauntlet",
        icon: TEW.ICONS_IDS.WEAPON_GAUNTLET,
        group: "BRAWLING",
        groupLabel: "Brawling",
        price: "2/0/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["IMPALE", "UNBALANCED"],
        description: "empty"
    },
    BOAT_HOOK: {
        name: "Boat Hook",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "BRAWLING",
        groupLabel: "Brawling",
        price: "0/6/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["TRIP", "UNDAMAGING"],
        description: "empty"
    },
    GARROTE: {
        name: "Garrote",
        icon: TEW.ICONS_IDS.WEAPON_CHAINS,
        group: "BRAWLING",
        groupLabel: "Brawling",
        price: "0/1/0",
        enc: 0,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["ENTANGLE", "SLOW", "UNBALANCED", "UNDAMAGING"],
        description: "empty"
    },
    UNARMED: {
        name: "Unarmed",
        icon: TEW.ICONS_IDS.WEAPON_GAUNTLET,
        group: "BRAWLING",
        groupLabel: "Brawling",
        price: "0/0/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: ["UNDAMAGING"],
        description: "empty"
    },
    KNUCKLEDUSTERS: {
        name: "Knuckledusters",
        group: "BRAWLING",
        groupLabel: "Brawling",
        price: "0/2/6",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "empty"
    },
    LOCKED_GAUNTLET: {
        name: "Locked Gauntlet",
        icon: TEW.ICONS_IDS.WEAPON_CLAW,
        group: "BRAWLING",
        groupLabel: "Brawling",
        price: "1/0/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["UNDAMAGING"],
        description: "empty"
    },
    SAP: {
        name: "Sap",
        icon: TEW.ICONS_IDS.WEAPON_GAUNTLET,
        group: "BRAWLING",
        groupLabel: "Brawling",
        price: "0/1/0",
        enc: 0,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: ["PUMMEL", "UNBALANCED", "UNDAMAGING"],
        description: "empty"
    },
    GRAIN_FLAIL: {
        name: "Grain Flail",
        icon: TEW.ICONS_IDS.WEAPON_FLAIL,
        group: "FLAIL",
        groupLabel: "Flail",
        price: "0/10/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["DISTRACT", "IMPRECISE", "WRAP"],
        description: "empty"
    },
    FLAIL: {
        name: "Flail",
        icon: TEW.ICONS_IDS.WEAPON_FLAIL,
        group: "FLAIL",
        groupLabel: "Flail",
        price: "2/0/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 5,
        qualities: ["DISTRACT", "WRAP"],
        description: "empty"
    },
    MILITARY_FLAIL: {
        name: "Military Flail",
        icon: TEW.ICONS_IDS.WEAPON_FLAIL,
        group: "FLAIL",
        groupLabel: "Flail",
        price: "3/0/0",
        enc: 2,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: ["DISTRACT", "IMPRECISE", "TIRING", "WRAP"],
        description: "empty"
    },
    CLOAK: {
        name: "Cloak",
        icon: TEW.ICONS_IDS.WEAPON_CHAINS,
        group: "PARRY",
        groupLabel: "Parry",
        price: "0/10/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: ["ENTANGLE", "DEFENSIVE", "UNDAMAGING"],
        description: "empty"
    },
    MAIN_GAUCHE: {
        name: "Main Gauche",
        icon: TEW.ICONS_IDS.WEAPON_KNIFE,
        group: "PARRY",
        groupLabel: "Parry",
        price: "1/0/0",
        enc: 0,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["DEFENSIVE"],
        description: "empty"
    },
    SWORDBREAKER: {
        name: "Swordbreaker",
        icon: TEW.ICONS_IDS.WEAPON_BREAKER,
        group: "PARRY",
        groupLabel: "Parry",
        price: "1/2/6",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["DEFENSIVE", "TRAP_BLADE"],
        description: "empty"
    },
    WEIGHTED_NET: {
        name: "Weighted Net",
        icon: TEW.ICONS_IDS.WEAPON_CHAINS,
        group: "PARRY",
        groupLabel: "Parry",
        price: "0/10/0",
        enc: 1,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: ["ENTANGLE", "DEFENSIVE", "SHIELD_1", "SLOW", "UNDAMAGING", "WRAP"],
        description: "empty"
    },
    AHLSPIESS: {
        name: "Ahlspiess",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "2/0/0",
        enc: 2,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 3,
        qualities: ["IMPALE", "PENETRATING"],
        description: "empty"
    },
    BILL: {
        name: "Bill",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "2/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE", "HACK", "TRIP"],
        description: "empty"
    },
    HALBERD: {
        name: "Halberd",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "2/0/0",
        enc: 3,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE", "HACK", "IMPALE"],
        description: "empty"
    },
    MANCATCHER: {
        name: "Mancatcher",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "2/0/0",
        enc: 3,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 2,
        qualities: ["DEFENSIVE", "ENTANGLE"],
        description: "empty"
    },
    PARTIZAN: {
        name: "Partizan",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "2/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE", "IMPALE", "SLASH_2"], // TODO Impale OR Slash
        description: "empty"
    },
    POLLAXE: {
        name: "Pollaxe",
        icon: TEW.ICONS_IDS.WEAPON_AXE,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "2/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE", "HACK", "IMPALE", "PUMMEL"], // TODO Hack OR Impale OR Pummel
        description: "empty"
    },
    SPEAR: {
        name: "Spear",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "0/15/0",
        enc: 2,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["IMPALE"],
        description: "empty"
    },
    PIKE: {
        name: "Pike",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "0/18/0",
        enc: 4,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["IMPALE"],
        description: "empty"
    },
    QUARTERSTAFF: {
        name: "Quarterstaff",
        icon: TEW.ICONS_IDS.WEAPON_STAFF,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "0/3/0",
        enc: 2,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE", "PUMMEL"],
        description: "empty"
    },
    ENCHANTED_STAFF: {
        name: "Enchanted Staff",
        icon: TEW.ICONS_IDS.WEAPON_STAFF,
        group: "POLE_ARM",
        groupLabel: "Pole arm",
        price: "15/0/0",
        enc: 2,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE", "PUMMEL"],
        description: "empty"
    },
    BASTARD_SWORD: {
        name: "Bastard Sword",
        icon: TEW.ICONS_IDS.WEAPON_SWORD,
        group: "TWO_HANDED",
        groupLabel: "Two handed",
        price: "8/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["DAMAGING", "DEFENSIVE"],
        description: "empty"
    },
    GREAT_AXE: {
        name: "Great Axe",
        icon: TEW.ICONS_IDS.WEAPON_AXE,
        group: "TWO_HANDED",
        groupLabel: "Two handed",
        price: "4/0/0",
        enc: 3,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: ["HACK", "IMPACT", "TIRING"],
        description: "empty"
    },
    FLAMBERGE_ZWEIHANDER: {
        name: "Flamberge Zweihander",
        icon: TEW.ICONS_IDS.WEAPON_SWORD,
        group: "TWO_HANDED",
        groupLabel: "Two handed",
        price: "30/0/0",
        enc: 3,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["DAMAGING", "HACK", "SLASH_2"],
        description: "empty"
    },
    PICK: {
        name: "Pick",
        icon: TEW.ICONS_IDS.WEAPON_MACE,
        group: "TWO_HANDED",
        groupLabel: "Two handed",
        price: "0/9/0",
        enc: 3,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 5,
        qualities: ["DAMAGING", "IMPALE", "SLOW"],
        description: "empty"
    },
    WARHAMMER_TH: {
        name: "Warhammer",
        icon: TEW.ICONS_IDS.WEAPON_MACE,
        group: "TWO_HANDED",
        groupLabel: "Two handed",
        price: "3/0/0",
        enc: 3,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 6,
        qualities: ["DAMAGING", "PUMMEL", "SLOW"],
        description: "empty"
    },
    ZWEIHANDER: {
        name: "Zweihander",
        icon: TEW.ICONS_IDS.WEAPON_SWORD,
        group: "TWO_HANDED",
        groupLabel: "Two handed",
        price: "10/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["DAMAGING", "HACK"],
        description: "empty"
    }
};

TEW.RANGED_WEAPONS = TEW.RANGED_WEAPONS || {
    ELF_BOW: {
        name: "Elf Bow",
        icon: TEW.ICONS_IDS.WEAPON_BOW,
        group: "BOW",
        groupLabel: "Bow",
        twoHanded: true,
        price: "10/0/0",
        enc: 2,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: 150,
        strBonus: true,
        damage: 4,
        qualities: ["DAMAGING", "PRECISE"],
        description: "empty"
    },
    LONGBOW: {
        name: "Longbow",
        icon: TEW.ICONS_IDS.WEAPON_BOW,
        group: "BOW",
        groupLabel: "Bow",
        twoHanded: true,
        price: "5/0/0",
        enc: 3,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: 100,
        strBonus: true,
        damage: 4,
        qualities: ["DAMAGING"],
        description: "empty"
    },
    BOW: {
        name: "Bow",
        icon: TEW.ICONS_IDS.WEAPON_BOW,
        group: "BOW",
        groupLabel: "Bow",
        twoHanded: true,
        price: "4/0/0",
        enc: 2,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: 50,
        strBonus: true,
        damage: 3,
        qualities: [],
        description: "empty"
    },
    SHORTBOW: {
        name: "Shortbow",
        icon: TEW.ICONS_IDS.WEAPON_BOW,
        group: "BOW",
        groupLabel: "Bow",
        twoHanded: true,
        price: "3/0/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: 20,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "empty"
    },
    CROSSBOW_PISTOL: {
        name: "Crossbow Pistol",
        icon: TEW.ICONS_IDS.WEAPON_CROSSBOW,
        group: "CROSSBOW",
        groupLabel: "Crossbow",
        twoHanded: false,
        price: "6/0/0",
        enc: 0,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: 10,
        strBonus: false,
        damage: 7,
        qualities: ["PISTOL"],
        description: "empty"
    },
    HEAVY_CROSSBOW: {
        name: "Heavy Crossbow",
        icon: TEW.ICONS_IDS.WEAPON_CROSSBOW,
        group: "CROSSBOW",
        groupLabel: "Crossbow",
        twoHanded: true,
        price: "7/0/0",
        enc: 3,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        range: 100,
        strBonus: false,
        damage: 9,
        qualities: ["DAMAGING", "RELOAD_2"],
        description: "empty"
    },
    CROSSBOW: {
        name: "Crossbow",
        icon: TEW.ICONS_IDS.WEAPON_CROSSBOW,
        group: "CROSSBOW",
        groupLabel: "Crossbow",
        twoHanded: true,
        price: "5/0/0",
        enc: 2,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: 60,
        strBonus: false,
        damage: 9,
        qualities: ["RELOAD_1"],
        description: "empty"
    },
    LASSO: {
        name: "Lasso",
        icon: TEW.ICONS_IDS.WEAPON_WHIP,
        group: "ENTANGLING",
        groupLabel: "Entangling",
        twoHanded: false,
        price: "0/6/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: 6,
        strBonus: false,
        damage: 0,
        qualities: ["ENTANGLE"],
        description: "empty"
    },
    WHIP: {
        name: "Whip",
        icon: TEW.ICONS_IDS.WEAPON_WHIP,
        group: "ENTANGLING",
        groupLabel: "Entangling",
        twoHanded: false,
        price: "0/5/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: 6,
        strBonus: true,
        damage: 2,
        qualities: ["ENTANGLE"],
        description: "empty"
    },
    SLING: {
        name: "Sling",
        icon: TEW.ICONS_IDS.WEAPON_SLING,
        group: "SLING",
        groupLabel: "Sling",
        twoHanded: false,
        price: "0/1/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: 60,
        strBonus: false,
        damage: 6,
        qualities: [],
        description: "empty"
    },
    STAFF_SLING: {
        name: "Staff Sling",
        icon: TEW.ICONS_IDS.WEAPON_SLING,
        group: "SLING",
        groupLabel: "Sling",
        twoHanded: true,
        price: "0/4/0",
        enc: 2,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: 100,
        strBonus: false,
        damage: 7,
        qualities: [],
        description: "empty"
    },
    BOLAS: {
        name: "Bolas",
        icon: TEW.ICONS_IDS.WEAPON_CHAINS,
        group: "THROWING",
        groupLabel: "Throwing",
        twoHanded: false,
        price: "0/1/0",
        enc: 0,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        range: 9,
        strBonus: true,
        damage: 0,
        qualities: ["ENTANGLE"],
        description: "empty"
    },
    DART: {
        name: "Dart",
        icon: TEW.ICONS_IDS.WEAPON_SLING,
        group: "THROWING",
        groupLabel: "Throwing",
        twoHanded: false,
        price: "0/2/0",
        enc: 0,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: 6,
        strBonus: true,
        damage: 1,
        qualities: ["IMPALE"],
        description: "empty"
    },
    JAVELIN: {
        name: "Javelin",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "THROWING",
        groupLabel: "Throwing",
        twoHanded: false,
        price: "0/10/6",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: 9,
        strBonus: true,
        damage: 3,
        qualities: ["IMPALE"],
        description: "empty"
    },
    ROCK: {
        name: "Rock",
        icon: TEW.ICONS_IDS.WEAPON_GAUNTLET,
        group: "THROWING",
        groupLabel: "Throwing",
        twoHanded: false,
        price: "0/0/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: 9,
        strBonus: true,
        damage: 0,
        qualities: [],
        description: "empty"
    },
    THROWING_AXE: {
        name: "Throwing Axe",
        icon: TEW.ICONS_IDS.WEAPON_AXE,
        group: "THROWING",
        groupLabel: "Throwing",
        twoHanded: false,
        price: "1/0/0",
        enc: 1,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: 6,
        strBonus: true,
        damage: 3,
        qualities: ["HACK"],
        description: "empty"
    },
    THROWING_KNIFE: {
        name: "Throwing Knife",
        icon: TEW.ICONS_IDS.WEAPON_KNIFE,
        group: "THROWING",
        groupLabel: "Throwing",
        twoHanded: false,
        price: "0/18/0",
        enc: 0,
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: 6,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "empty"
    },
    BOMB: {
        name: "Bomb",
        icon: TEW.ICONS_IDS.WEAPON_BOMB,
        group: "EXPLOSIVES",
        groupLabel: "Explosives",
        twoHanded: false,
        price: "3/0/0",
        enc: 0,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        range: 3,
        strBonus: false,
        damage: 12,
        qualities: ["BLAST_5", "DANGEROUS", "IMPACT"],
        description: "empty"
    },
    INCENDIARY: {
        name: "Incendiary",
        icon: TEW.ICONS_IDS.WEAPON_BOMB,
        group: "EXPLOSIVES",
        groupLabel: "Explosives",
        twoHanded: false,
        price: "1/0/0",
        enc: 0,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: 3,
        strBonus: false,
        damage: 0, // TODO
        qualities: ["BLAST_4", "DANGEROUS"],
        description: "empty"
    },
    BLUNDERBUSS: {
        name: "Blunderbuss",
        icon: TEW.ICONS_IDS.WEAPON_SHOTGUN,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: true,
        price: "2/0/0",
        enc: 1,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: 20,
        strBonus: false,
        damage: 8,
        qualities: ["DANGEROUS", "RELOAD_2"],
        description: "empty"
    },
    HOCHLAND_LONG_RIFLE: {
        name: "Hochland Long Rifle",
        icon: TEW.ICONS_IDS.WEAPON_RIFLE,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: true,
        price: "100/0/0",
        enc: 3,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: 100,
        strBonus: false,
        damage: 9,
        qualities: ["ACCURATE", "PRECISE", "RELOAD_4"],
        description: "empty"
    },
    HANDGUN: {
        name: "Handgun",
        icon: TEW.ICONS_IDS.WEAPON_PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: true,
        price: "4/0/0",
        enc: 2,
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: 50,
        strBonus: false,
        damage: 9,
        qualities: ["DANGEROUS", "RELOAD_3"],
        description: "empty"
    },
    PISTOL: {
        name: "Pistol",
        icon: TEW.ICONS_IDS.WEAPON_PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: false,
        price: "8/0/0",
        enc: 0,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        range: 20,
        strBonus: false,
        damage: 8,
        qualities: ["PISTOL", "RELOAD_1"],
        description: "empty"
    },
    MATCHLOCK_HANDGUN: {
        name: "Matchlock Handgun",
        icon: TEW.ICONS_IDS.WEAPON_PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: true,
        price: "2/0/0",
        enc: 2,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        range: 50,
        strBonus: false,
        damage: 8,
        qualities: ["DANGEROUS", "RELOAD_4"],
        description: "empty"
    },
    MATCHLOCK_BLUNDERBUSS: {
        name: "Matchlock Blunderbuss",
        icon: TEW.ICONS_IDS.WEAPON_SHOTGUN,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: true,
        price: "1/0/0",
        enc: 1,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        range: 20,
        strBonus: false,
        damage: 7,
        qualities: ["SPREAD_3", "DANGEROUS", "RELOAD_3"],
        description: "empty"
    },
    ARQUEBUS: {
        name: "Arquebus",
        icon: TEW.ICONS_IDS.WEAPON_RIFLE,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: true,
        price: "5/0/0",
        enc: 3,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: 40,
        strBonus: false,
        damage: 9,
        qualities: ["DANGEROUS", "IMPRECISE", "RELOAD_5"],
        description: "empty"
    },
    DOUBLE_BARRELLED_HANDGUN: {
        name: "Double-Barrelled Handgun",
        icon: TEW.ICONS_IDS.WEAPON_PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: true,
        price: "7/0/0",
        enc: 3,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: 50,
        strBonus: false,
        damage: 9,
        qualities: ["DANGEROUS", "REPEATER", "RELOAD_4"],
        description: "empty"
    },
    GRIFFONSFOOT_PISTOL: {
        name: "Griffonsfoot Pistol",
        icon: TEW.ICONS_IDS.WEAPON_PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: false,
        price: "10/0/0",
        enc: 1,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: 10,
        strBonus: false,
        damage: 7,
        qualities: ["IMPRECISE", "SPREAD_5", "RELOAD_6"],
        description: "empty"
    },
    GUN_AXE: {
        name: "GunAxe",
        icon: TEW.ICONS_IDS.WEAPON_AXE,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: true,
        price: "8/0/0",
        enc: 1,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: 30,
        strBonus: false,
        damage: 9,
        qualities: ["DANGEROUS", "IMPRECISE", "RELOAD_4"],
        description: "empty"
    },
    GUN_HALBERD: {
        name: "Gun Halberd",
        icon: TEW.ICONS_IDS.WEAPON_SPEAR,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        twoHanded: true,
        price: "10/0/0",
        enc: 3,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: 30,
        strBonus: false,
        damage: 9,
        qualities: ["DANGEROUS", "IMPRECISE", "RELOAD_4"],
        description: "empty"
    },
    REPEATER_HANDGUN: {
        name: "Repeater Handgun",
        icon: TEW.ICONS_IDS.WEAPON_PISTOL,
        group: "ENGINEERING",
        groupLabel: "Engineering",
        twoHanded: true,
        price: "10/0/0",
        enc: 3,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        range: 30,
        strBonus: false,
        damage: 9,
        qualities: ["DANGEROUS", "RELOAD_5", "REPEATER_4"],
        description: "empty"
    },
    REPEATER_PISTOL: {
        name: "Repeater Pistol",
        icon: TEW.ICONS_IDS.WEAPON_PISTOL,
        group: "ENGINEERING",
        groupLabel: "Engineering",
        twoHanded: false,
        price: "15/0/0",
        enc: 1,
        availability: "RARE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_RARE,
        range: 10,
        strBonus: false,
        damage: 8,
        qualities: ["DANGEROUS", "PISTOL", "RELOAD_4", "REPEATER_4"],
        description: "empty"
    },
    HAND_MORTAR: {
        name: "Hand Mortar",
        icon: TEW.ICONS_IDS.WEAPON_PISTOL,
        group: "ENGINEERING",
        groupLabel: "Engineering",
        twoHanded: true,
        price: "50/0/0",
        enc: 3,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: 30,
        strBonus: false,
        damage: 7,
        qualities: ["DANGEROUS", "IMPRECISE", "RELOAD_2"],
        description: "empty"
    },
    CANE_PISTOL: {
        name: "Cane Pistol",
        icon: TEW.ICONS_IDS.WEAPON_PISTOL,
        group: "ENGINEERING",
        groupLabel: "Engineering",
        twoHanded: false,
        price: "15/0/0",
        enc: 3,
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: 10,
        strBonus: false,
        damage: 8,
        qualities: ["DANGEROUS", "IMPRECISE", "RELOAD_6"],
        description: "empty"
    }
};

TEW.AMMUNITION = TEW.AMMUNITION || {
    ARROW: {
        name: "Arrow",
        icon: TEW.ICONS_IDS.WEAPON_BOW,
        group: "BOW",
        groupLabel: "Bow",
        ammountSold: 12,
        price: "0/5/0",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: ["IMPALE"],
        description: "empty"
    },
    BARBED_ARROW: {
        name: "Barbed Arrow",
        icon: TEW.ICONS_IDS.WEAPON_BOW,
        group: "BOW",
        groupLabel: "Bow",
        ammountSold: 12,
        price: "0/8/0",
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+0",
        qualities: ["IMPALE", "SLASH_1"],
        description: "empty"
    },
    BODKIN_ARROW: {
        name: "Bodkin Arrow",
        icon: TEW.ICONS_IDS.WEAPON_BOW,
        group: "BOW",
        groupLabel: "Bow",
        ammountSold: 12,
        price: "0/8/0",
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+0",
        qualities: ["IMPALE", "PENETRATING"],
        description: "empty"
    },
    ELF_ARROW: {
        name: "Elf Arrow",
        icon: TEW.ICONS_IDS.WEAPON_BOW,
        group: "BOW",
        groupLabel: "Bow",
        ammountSold: 1,
        price: "0/6/0",
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: "+50",
        damage: "+1",
        qualities: ["ACCURATE", "IMPALE", "PENETRATING"],
        description: "empty"
    },
    SHARO_STICK: {
        name: "Sharp Stick",
        icon: TEW.ICONS_IDS.WEAPON_BOW,
        group: "BOW",
        groupLabel: "Bow",
        ammountSold: 1,
        price: "0/0/0",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "/2",
        damage: "-2",
        qualities: ["DANGEROUS", "IMPRECISE", "UNDAMAGING"],
        description: "empty"
    },
    BOLT: {
        name: "Bolt",
        icon: TEW.ICONS_IDS.WEAPON_CROSSBOW,
        group: "CROSSBOW",
        groupLabel: "Crossbow",
        ammountSold: 12,
        price: "0/5/0",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: ["IMPALE"],
        description: "empty"
    },
    LEAD_BULLET: {
        name: "Lead Bullet",
        icon: TEW.ICONS_IDS.WEAPON_SLING,
        group: "SLING",
        groupLabel: "Sling",
        ammountSold: 12,
        price: "0/0/4",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "-10",
        damage: "+1",
        qualities: ["PUMMEL"],
        description: "empty"
    },
    PEBBLE: {
        name: "Pebble",
        icon: TEW.ICONS_IDS.WEAPON_SLING,
        group: "SLING",
        groupLabel: "Sling",
        ammountSold: 1,
        price: "0/0/0",
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: "-10",
        damage: "-2",
        qualities: ["IMPRECISE", "UNDAMAGING"],
        description: "empty"
    },
    STONE_BULLET: {
        name: "Stone Bullet",
        icon: TEW.ICONS_IDS.WEAPON_SLING,
        group: "SLING",
        groupLabel: "Sling",
        ammountSold: 12,
        price: "0/0/2",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: ["PUMMEL"],
        description: "empty"
    },
    BULLET_AND_POWDER: {
        name: "Bullet and Powder",
        icon: TEW.ICONS_IDS.PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        ammountSold: 12,
        price: "0/3/3",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+1",
        qualities: ["IMPALE", "PENETRATING"],
        description: "empty"
    },
    PAPER_CARTRIDGE: {
        name: "Paper Cartridge",
        icon: TEW.ICONS_IDS.PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        ammountSold: 12,
        price: "0/5/0",
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+1",
        qualities: ["IMPALE", "PENETRATING", "FASTER_RELOAD"],
        description: "empty"
    },
    AQSHY_INFUSED_POWDER: {
        name: "Aqshy-Infused Powder",
        icon: TEW.ICONS_IDS.PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        ammountSold: 12,
        price: "1/0/0",
        availability: "EXOTIC",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_EXOTIC,
        range: "+10",
        damage: "+2",
        qualities: ["IMPALE", "PENETRATING"],
        description: "empty"
    },
    PRECISION_SHOT_AND_POWDER: {
        name: "Precision Shot and Powder",
        icon: TEW.ICONS_IDS.PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        ammountSold: 1,
        price: "0/3/0",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+1",
        qualities: ["IMPALE", "PENETRATING", "PRECISE"],
        description: "empty"
    },
    IMPROVISED_SHOT_AND_POWDER: {
        name: "Improvised Shot and Powder",
        icon: TEW.ICONS_IDS.PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        ammountSold: 1,
        price: "0/0/3",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "/2",
        damage: "+0",
        qualities: [],
        description: "empty"
    },
    SMALL_SHOT_AND_POWDER: {
        name: "Small Shot and Powder",
        icon: TEW.ICONS_IDS.PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        ammountSold: 12,
        price: "0/3/3",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: ["SPREAD_3"],
        description: "empty"
    },
    SCRAP_AND_POWDER: {
        name: "Scrap and Powder",
        icon: TEW.ICONS_IDS.PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        ammountSold: 12,
        price: "0/2/0",
        availability: "COMMON",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_COMMON,
        range: "/2",
        damage: "-1",
        qualities: ["SPREAD_3", "INFECTED"],
        description: "empty"
    },
    LARGE_BULLET_AND_POWDER: {
        name: "Large Bullet and Powder",
        icon: TEW.ICONS_IDS.PISTOL,
        group: "BLACKPOWDER",
        groupLabel: "Blackpowder",
        ammountSold: 12,
        price: "1/0/0",
        availability: "SCARCE",
        availabilityIcon: TEW.ICONS_IDS.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+2",
        qualities: ["IMPALE", "IMPACT", "PENETRATING"],
        description: "empty"
    }
};

TEW.WEAPON_IDS = Object.keys(TEW.MELEE_WEAPONS).sort((a, b) => a.localeCompare(b))
        .concat(Object.keys(TEW.RANGED_WEAPONS).sort((a, b) => a.localeCompare(b)));
TEW.WEAPONS_ARRAY = Object.entries(TEW.MELEE_WEAPONS).sort((a, b) => a[0].localeCompare(b[0]))
        .concat(Object.entries(TEW.RANGED_WEAPONS).sort((a, b) => a[0].localeCompare(b[0])));
