// $PluginCompiler TEW_Constants.js

import { ArmorGroup, ArmorGroupLabel, BodyLocation, ArmorQuality, Availability } from "../types/enum";
import TEW from "../types/tew";

// $StartCompilation
TEW.DATABASE.ARMORS = {};
TEW.DATABASE.ARMORS.SET = {
    SOFT_KIT: {
        name: "Soft Kit",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_LIGHT_BODY_SLOT,
        group: ArmorGroup.SOFT_KIT,
        groupLabel: ArmorGroupLabel.SOFT_KIT,
        price: "0/18/0",
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        penalty: [],
        locations: [BodyLocation.ARMS, BodyLocation.BODY, BodyLocation.LEGS],
        ap: 0,
        qualities: [],
        forbiddenWith: [],
        description: "Description has to be done."
    },
    REINFORCED_SOFT_KIT: {
        name: "Reinforced Soft Kit",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_BODY_SLOT,
        group: ArmorGroup.SOFT_KIT,
        groupLabel: ArmorGroupLabel.SOFT_KIT,
        price: "2/0/0",
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        penalty: [],
        locations: [BodyLocation.ARMS, BodyLocation.BODY, BodyLocation.LEGS],
        ap: 1,
        qualities: [ArmorQuality.PARTIAL, ArmorQuality.REINFORCED],
        forbiddenWith: [],
        description: "Description has to be done."
    },
    LEATHER_JACK: {
        name: "Leather Jack",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_LIGHT_BODY_SLOT,
        group: ArmorGroup.BOILED_LEATHER,
        groupLabel: ArmorGroupLabel.BOILED_LEATHER,
        price: "0/12/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        penalty: [],
        locations: [BodyLocation.ARMS, BodyLocation.BODY],
        ap: 1,
        qualities: [],
        forbiddenWith: [ArmorGroup.CHAINMAIL, ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    LEATHER_JERKIN: {
        name: "Leather Jerkin",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_LIGHT_BODY_SLOT,
        group: ArmorGroup.BOILED_LEATHER,
        groupLabel: ArmorGroupLabel.BOILED_LEATHER,
        price: "0/10/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        penalty: [],
        locations: [BodyLocation.BODY],
        ap: 1,
        qualities: [],
        forbiddenWith: [ArmorGroup.CHAINMAIL, ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    LEATHER_LEGGINGS: {
        name: "Leather Leggings",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_LIGHT_LEGS_SLOT,
        group: ArmorGroup.BOILED_LEATHER,
        groupLabel: ArmorGroupLabel.BOILED_LEATHER,
        price: "0/14/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        penalty: [],
        locations: [BodyLocation.LEGS],
        ap: 1,
        qualities: [],
        forbiddenWith: [ArmorGroup.CHAINMAIL, ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    LEATHER_SKULLCAP: {
        name: "Leather Skullcap",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_LIGHT_HEAD_SLOT,
        group: ArmorGroup.BOILED_LEATHER,
        groupLabel: ArmorGroupLabel.BOILED_LEATHER,
        price: "0/8/0",
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        penalty: [],
        locations: [BodyLocation.HEAD],
        ap: 1,
        qualities: [],
        forbiddenWith: [ArmorGroup.CHAINMAIL, ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    CHAINMAIL_CHAUSSES: {
        name: "Chainmail Chausses",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_LEGS_SLOT,
        group: ArmorGroup.CHAINMAIL,
        groupLabel: ArmorGroupLabel.CHAINMAIL,
        price: "2/0/0",
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        penalty: [{ STEALTH: "-10" }],
        locations: [BodyLocation.LEGS],
        ap: 2,
        qualities: [],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    CHAINMAIL_COAT: {
        name: "Chainmail Coat",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_BODY_SLOT,
        group: ArmorGroup.CHAINMAIL,
        groupLabel: ArmorGroupLabel.CHAINMAIL,
        price: "3/0/0",
        enc: 4,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        penalty: [{ STEALTH: "-10" }],
        locations: [BodyLocation.ARMS, BodyLocation.BODY],
        ap: 2,
        qualities: [],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    CHAINMAIL_COIF: {
        name: "Chainmail Coif",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_HEAD_SLOT,
        group: ArmorGroup.CHAINMAIL,
        groupLabel: ArmorGroupLabel.CHAINMAIL,
        price: "1/0/0",
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        penalty: [{ PERCEPTION: "-10", STEALTH: "-10" }],
        locations: [BodyLocation.HEAD],
        ap: 2,
        qualities: [ArmorQuality.PARTIAL],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    CHAINMAIL_SHIRT: {
        name: "Chainmail Shirt",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_BODY_SLOT,
        group: ArmorGroup.CHAINMAIL,
        groupLabel: ArmorGroupLabel.CHAINMAIL,
        price: "2/0/0",
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        penalty: [{ STEALTH: "-10" }],
        locations: [BodyLocation.BODY],
        ap: 2,
        qualities: [],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    BRIGANDINE_JACK: {
        name: "Brigandine Jack",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_LIGHT_BODY_SLOT,
        group: ArmorGroup.BRIGANDINE,
        groupLabel: ArmorGroupLabel.BRIGANDINE,
        price: "3/0/0",
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        penalty: [],
        locations: [BodyLocation.ARMS, BodyLocation.BODY],
        ap: 2,
        qualities: [ArmorQuality.OVERCOAT],
        forbiddenWith: [ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    BRIGANDINE_JERKIN: {
        name: "Brigandine Jerkin",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_LIGHT_BODY_SLOT,
        group: ArmorGroup.BRIGANDINE,
        groupLabel: ArmorGroupLabel.BRIGANDINE,
        price: "2/0/0",
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        penalty: [],
        locations: [BodyLocation.BODY],
        ap: 2,
        qualities: [ArmorQuality.OVERCOAT],
        forbiddenWith: [ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    BREASTPLATE: {
        name: "Breastplate",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_BODY_SLOT,
        group: ArmorGroup.BREASTPLATE,
        groupLabel: ArmorGroupLabel.BREASTPLATE,
        price: "10/0/0",
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        penalty: [],
        locations: [BodyLocation.BODY],
        ap: 3,
        qualities: [ArmorQuality.IMPENETRABLE, ArmorQuality.OVERCOAT, ArmorQuality.WEAKPOINTS],
        forbiddenWith: [ArmorGroup.PLATE],
        description: "Description has to be done."
    },
    BRACERS: {
        name: "Bracers",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_ARMS_SLOT,
        group: ArmorGroup.PLATE,
        groupLabel: ArmorGroupLabel.PLATE,
        price: "8/0/0",
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        penalty: [],
        locations: [BodyLocation.ARMS],
        ap: 3,
        qualities: [ArmorQuality.IMPENETRABLE, ArmorQuality.REQUIRES_KIT, ArmorQuality.WEAKPOINTS],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.CHAINMAIL, ArmorGroup.BRIGANDINE],
        description: "Description has to be done."
    },
    OPEN_HELM: {
        name: "Open Helm",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_HEAD_SLOT,
        group: ArmorGroup.PLATE,
        groupLabel: ArmorGroupLabel.PLATE,
        price: "2/0/0",
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        penalty: [{ PERCEPTION: "-10" }],
        locations: [BodyLocation.HEAD],
        ap: 3,
        qualities: [ArmorQuality.PARTIAL],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.CHAINMAIL, ArmorGroup.BRIGANDINE],
        description: "Description has to be done."
    },
    PLATE_LEGGINGS: {
        name: "Plate Leggings",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_LEGS_SLOT,
        group: ArmorGroup.PLATE,
        groupLabel: ArmorGroupLabel.PLATE,
        price: "10/0/0",
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        penalty: [{ STEALTH: "-10" }],
        locations: [BodyLocation.LEGS],
        ap: 3,
        qualities: [ArmorQuality.IMPENETRABLE, ArmorQuality.REQUIRES_KIT, ArmorQuality.WEAKPOINTS],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.CHAINMAIL, ArmorGroup.BRIGANDINE],
        description: "Description has to be done."
    },
    GREAT_HELM: {
        name: "Great Helm",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_HEAD_SLOT,
        group: ArmorGroup.PLATE,
        groupLabel: ArmorGroupLabel.PLATE,
        price: "2/0/0",
        enc: 2,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        penalty: [{ PERCEPTION: "-20" }],
        locations: [BodyLocation.HEAD],
        ap: 3,
        qualities: [ArmorQuality.IMPENETRABLE, ArmorQuality.WEAKPOINTS],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.CHAINMAIL, ArmorGroup.BRIGANDINE],
        description: "The Great Helm is the archetypal form of a fully enclosed metal helmet. They are considered old fashioned in Tilea and the Empire but are still common in Bretonnia. Early examples of these helmets had a square top. Later designs tend to have a conical top which lessens the impact of hammers and swords."
    },
    BASCINET: {
        name: "Bascinet",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_HEAD_SLOT,
        group: ArmorGroup.PLATE,
        groupLabel: ArmorGroupLabel.PLATE,
        price: "3/0/0",
        enc: 2,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        penalty: [{ PERCEPTION: "-20" }],
        locations: [BodyLocation.HEAD],
        ap: 3,
        qualities: [ArmorQuality.IMPENETRABLE, ArmorQuality.VISOR, ArmorQuality.WEAKPOINTS],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.CHAINMAIL, ArmorGroup.BRIGANDINE],
        description: "The Bascinet typically incorporates a conical ArmorQuality.VISOR, leading it to be known as a ‘pigs-snout’ helmet by many soldiers. This design provides additional protection against missile fire, as slingshots and arrows are deflected by the conical ArmorQuality.VISOR. If missile fire strikes the wearer of a Bascinet, and originates from in front of the wearer, then the helmet provides 4 APs rather than 3."
    },
    ARMET: {
        name: "Armet",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_HEAD_SLOT,
        group: ArmorGroup.PLATE,
        groupLabel: ArmorGroupLabel.PLATE,
        price: "3/0/0",
        enc: 2,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        penalty: [{ PERCEPTION: "-20" }],
        locations: [BodyLocation.HEAD],
        ap: 3,
        qualities: [ArmorQuality.IMPENETRABLE, ArmorQuality.VISOR, ArmorQuality.WEAKPOINTS],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER, ArmorGroup.CHAINMAIL, ArmorGroup.BRIGANDINE],
        description: "The Armet is a Tilean design which fits closely on the head, being narrower around the neck. To facilitate the snug fit the helmet has an integral mechanism that must be worked to open and close it. The exacting design of the Armet means that it can withstand blows that might damage other helmets. Every time the helmet might lose a point of AP, roll on the Armet Damage table."
    },
    SALLET: {
        name: "Sallet",
        icon: TEW.DATABASE.ICONS.SET.ARMOR_HEAVY_HEAD_SLOT,
        group: ArmorGroup.PLATE,
        groupLabel: ArmorGroupLabel.PLATE,
        price: "4/0/0",
        enc: 2,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        penalty: [{
            PERCEPTION: "-20"
        }],
        locations: [BodyLocation.HEAD],
        ap: 3,
        qualities: [ArmorQuality.IMPENETRABLE,ArmorQuality.VISOR,ArmorQuality.WEAKPOINTS],
        forbiddenWith: [ArmorGroup.BOILED_LEATHER,ArmorGroup.CHAINMAIL,ArmorGroup.BRIGANDINE],
        description: "The Sallet is typified by having heavy plates projecting over the neck to the back, and being combined with separate pieces, either a gorget or bevor, to provide protection to the throat, chin, and face. A wearer of a Sallet who takes a Critical Hit to the head will take 1 less Wound from the Critical Hit than they otherwise would."
    }
};

// TODO order in inventory ?
TEW.DATABASE.ARMORS.IDS = Object.keys(TEW.DATABASE.ARMORS.SET).sort((a, b) => a.localeCompare(b));

// Make an array based on the TEW.ARMORS object for easy access
TEW.DATABASE.ARMORS.ARRAY = TEW.DATABASE.ARMORS.IDS.map((key: string) => [key, TEW.DATABASE.ARMORS.SET[key]]);
