// $PluginCompiler TEW_Constants.js

import { WeaponGroup, WeaponGroupLabel, WeaponQuality, Availability } from "../types/enum";
import TEW from "../types/tew";

// $StartCompilation
TEW.DATABASE.WEAPONS = {};
// #region ====== WEAPONS MELEE SET === //
TEW.DATABASE.WEAPONS.MELEE_SET =  {
    AXE: {
        name: "Axe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 120,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.HACK, WeaponQuality.UNBALANCED],
        description: "Much beloved of Dwarfs, the axe is not as agile in the hand as a sword but the heavy cleaving head can make a mess of armour and shields."
    },
    BALLOCK_KNIFE: {
        name: "Ballock Knife",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 192,
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING, WeaponQuality.PRECISE],
        description: "The short, slim blade of a ballock knife makes for a poor weapon, unless you have a heavily armoured opponent at your mercy."
    },
    CLUB: {
        name: "Club",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 48,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.UNDAMAGING, WeaponQuality.UNBALANCED],
        description: "Clubs are as often found as they are crafted."
    },
    DAGGER: {
        name: "Dagger",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 192,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "These blades are crafted specifically for fighting."
    },
    IMPROVISED_WEAPON: {
        name: "Improvised Weapon",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PIPE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 0,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.UNDAMAGING, WeaponQuality.UNBALANCED],
        description: "Hard and heavy items that are not intended to be used as a weapon may still serve in a desperate moment. This entry covers such items as chair legs, rocks, snooker cues, and bottles."
    },
    KNIFE: {
        name: "Knife",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 96,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.UNDAMAGING],
        description: "This entry covers short, sharp blades intended for purposes other than fighting, such as kitchen or hunting knives."
    },
    MACE: {
        name: "Mace",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 180,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.PUMMEL, WeaponQuality.UNBALANCED],
        description: "The typical mace is a metal shaft with a heavy head shaped in flanges or spiked protrusions. Whilst it is less wieldy than a sword it inflicts concussive blows."
    },
    MILITARY_PICK: {
        name: "Military Pick",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 180,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.PENETRATING, WeaponQuality.UNBALANCED],
        description: "Crude picks are little more than a metal spike on the end of a stick, though better made weapons are fashioned from steel. They are not agile weapons but are well designed to crack armour."
    },
    SCIMITAR: {
        name: "Scimitar",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SABER,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 240,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.SLASH_1],
        description: "Popular in the east of the Empire, Kislev and Araby, the scimitar has a curved blade which can inflict terrible cutting wounds. Its design does compromise the welder’s ability to lunge and thrust, meaning that even though scimitars are a similar length to straight swords they have a shorter reach."
    },
    SWORD: {
        name: "Sword",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SWORD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 240,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [],
        description: "The sword is the weapon by which all others are measured. A quality sword has a needle point tip for thrusting, a blade that is razor sharp to either side, and is balanced so that the weight is close to the hand, making it agile for attack and defence."
    },
    WARHAMMER: {
        name: "Warhammer",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 240,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.PENETRATING, WeaponQuality.PUMMEL, WeaponQuality.UNBALANCED],
        description: "Warhammers come in several designs, but typically have a flat heavy head on one side for inflicting pummelling damage, and a spiked point on the other for penetrating armour."
    },
    SHIELD_BUCKLER: {
        name: "Shield (Buckler)",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHIELD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 218,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        strBonus: true,
        longReach: false,
        damage: 1,
        qualities: [WeaponQuality.SHIELD_1, WeaponQuality.DEFENSIVE, WeaponQuality.UNDAMAGING],
        description: "A small shield to save you from harm."
    },
    SHIELD: {
        name: "Shield",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHIELD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 480,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.SHIELD_2, WeaponQuality.DEFENSIVE, WeaponQuality.UNDAMAGING],
        description: "A regular shield, ideal for close combat."
    },
    SHIELD_LARGE: {
        name: "Shield (Large)",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHIELD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 720,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.SHIELD_3, WeaponQuality.DEFENSIVE, WeaponQuality.UNDAMAGING],
        description: "A large shield to protect you from all enemies"
    },
    PAVISE: {
        name: "Pavise",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHIELD,
        group: WeaponGroup.BASIC,
        groupLabel: WeaponGroupLabel.BASIC,
        price: 900,
        enc: 4,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.SHIELD_5],
        description: "The pavise is a large shield carried by crossbowmen to provide shelter on the battlefield as they reload. Roughly 4 feet tall and often painted with the unit’s coat of arms, the crossbowman plants the pavise on the ground like a personal wall."
    },
    CAVALRY_HAMMER: {
        name: "Cavalry Hammer",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.CAVALRY,
        groupLabel: WeaponGroupLabel.CAVALRY,
        price: 720,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.PUMMEL],
        description: "Cavalry hammers are large, weighty weapons, favoured by the Knights of the White Wolf. On foot, they may be used with the Melee (Two-Handed) skill."
    },
    DEMI_LANCE: {
        name: "Demi-Lance",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.CAVALRY,
        groupLabel: WeaponGroupLabel.CAVALRY,
        price: 240,
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.IMPACT, WeaponQuality.IMPALE],
        description: "Lances resemble spears, but with a weighty grip designed to brace the weapon against the arm and chest of a charging knight. The demi-lance is similar, but shorter and lighter."
    },
    LANCE: {
        name: "Lance",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.CAVALRY,
        groupLabel: WeaponGroupLabel.CAVALRY,
        price: 240,
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: [WeaponQuality.IMPACT, WeaponQuality.IMPALE],
        description: "Lances resemble spears, but with a weighty grip designed to brace the weapon against the arm and chest of a charging knight. The demi-lance is similar, but shorter and lighter."
    },
    SABRE: {
        name: "Sabre",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SABER,
        group: WeaponGroup.CAVALRY,
        groupLabel: WeaponGroupLabel.CAVALRY,
        price: 120,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.SLASH_1],
        description: "empty"
    },
    FOIL: {
        name: "Foil",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FOIL,
        group: WeaponGroup.FENCING,
        groupLabel: WeaponGroupLabel.FENCING,
        price: 1200,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.FAST, WeaponQuality.IMPALE, WeaponQuality.PRECISE, WeaponQuality.UNDAMAGING],
        description: "empty"
    },
    RAPIER: {
        name: "Rapier",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_RAPIER,
        group: WeaponGroup.FENCING,
        groupLabel: WeaponGroupLabel.FENCING,
        price: 1200,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.FAST, WeaponQuality.IMPALE],
        description: "empty"
    },
    SMALLSWORD: {
        name: "Smallsword",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FOIL,
        group: WeaponGroup.FENCING,
        groupLabel: WeaponGroupLabel.FENCING,
        price: 960,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.FAST, WeaponQuality.IMPALE, WeaponQuality.PRECISE],
        description: "empty"
    },
    SPIKED_GAUNTLET: {
        name: "Spiked Gauntlet",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 480,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.IMPALE, WeaponQuality.UNBALANCED],
        description: "empty"
    },
    BOAT_HOOK: {
        name: "Boat Hook",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 72,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.TRIP, WeaponQuality.UNDAMAGING],
        description: "empty"
    },
    GARROTE: {
        name: "Garrote",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CHAINS,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 12,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.ENTANGLE, WeaponQuality.SLOW, WeaponQuality.UNBALANCED, WeaponQuality.UNDAMAGING],
        description: "empty"
    },
    UNARMED: {
        name: "Unarmed",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 0,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: [WeaponQuality.UNDAMAGING],
        description: "empty"
    },
    KNUCKLEDUSTERS: {
        name: "Knuckledusters",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 30,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "empty"
    },
    LOCKED_GAUNTLET: {
        name: "Locked Gauntlet",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CLAW,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 240,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.UNDAMAGING],
        description: "empty"
    },
    SAP: {
        name: "Sap",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.BRAWLING,
        groupLabel: WeaponGroupLabel.BRAWLING,
        price: 12,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.PUMMEL, WeaponQuality.UNBALANCED, WeaponQuality.UNDAMAGING],
        description: "empty"
    },
    GRAIN_FLAIL: {
        name: "Grain Flail",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FLAIL,
        group: WeaponGroup.FLAIL,
        groupLabel: WeaponGroupLabel.FLAIL,
        price: 120,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.DISTRACT, WeaponQuality.IMPRECISE, WeaponQuality.WRAP],
        description: "empty"
    },
    FLAIL: {
        name: WeaponGroupLabel.FLAIL,
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FLAIL,
        group: WeaponGroup.FLAIL,
        groupLabel: WeaponGroupLabel.FLAIL,
        price: 480,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DISTRACT, WeaponQuality.WRAP],
        description: "empty"
    },
    MILITARY_FLAIL: {
        name: "Military Flail",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_FLAIL,
        group: WeaponGroup.FLAIL,
        groupLabel: WeaponGroupLabel.FLAIL,
        price: 720,
        enc: 2,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: [WeaponQuality.DISTRACT, WeaponQuality.IMPRECISE, WeaponQuality.TIRING, WeaponQuality.WRAP],
        description: "empty"
    },
    CLOAK: {
        name: "Cloak",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CHAINS,
        group: WeaponGroup.PARRY,
        groupLabel: WeaponGroupLabel.PARRY,
        price: 120,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: [WeaponQuality.ENTANGLE, WeaponQuality.DEFENSIVE, WeaponQuality.UNDAMAGING],
        description: "empty"
    },
    MAIN_GAUCHE: {
        name: "Main Gauche",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.PARRY,
        groupLabel: WeaponGroupLabel.PARRY,
        price: 240,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.DEFENSIVE],
        description: "empty"
    },
    SWORDBREAKER: {
        name: "Swordbreaker",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BREAKER,
        group: WeaponGroup.PARRY,
        groupLabel: WeaponGroupLabel.PARRY,
        price: 270,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.TRAP_BLADE],
        description: "empty"
    },
    WEIGHTED_NET: {
        name: "Weighted Net",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CHAINS,
        group: WeaponGroup.PARRY,
        groupLabel: WeaponGroupLabel.PARRY,
        price: 120,
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: [WeaponQuality.ENTANGLE, WeaponQuality.DEFENSIVE, WeaponQuality.SHIELD_1, WeaponQuality.SLOW, WeaponQuality.UNDAMAGING, WeaponQuality.WRAP],
        description: "empty"
    },
    AHLSPIESS: {
        name: "Ahlspiess",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "empty"
    },
    BILL: {
        name: "Bill",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.HACK, WeaponQuality.TRIP],
        description: "empty"
    },
    HALBERD: {
        name: "Halberd",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.HACK, WeaponQuality.IMPALE],
        description: "empty"
    },
    MANCATCHER: {
        name: "Mancatcher",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.ENTANGLE],
        description: "empty"
    },
    PARTIZAN: {
        name: "Partizan",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.IMPALE, WeaponQuality.SLASH_2], // TODO Impale OR Slash
        description: "empty"
    },
    POLLAXE: {
        name: "Pollaxe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 480,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.HACK, WeaponQuality.IMPALE, WeaponQuality.PUMMEL], // TODO Hack OR Impale OR Pummel
        description: "empty"
    },
    SPEAR: {
        name: "Spear",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 180,
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.IMPALE],
        description: "empty"
    },
    PIKE: {
        name: "Pike",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 216,
        enc: 4,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.IMPALE],
        description: "empty"
    },
    QUARTERSTAFF: {
        name: "Quarterstaff",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_STAFF,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 36,
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.PUMMEL],
        description: "empty"
    },
    ENCHANTED_STAFF: {
        name: "Enchanted Staff",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_STAFF,
        group: WeaponGroup.POLE_ARM,
        groupLabel: WeaponGroupLabel.POLE_ARM,
        price: 3600,
        enc: 2,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DEFENSIVE, WeaponQuality.PUMMEL],
        description: "empty"
    },
    BASTARD_SWORD: {
        name: "Bastard Sword",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SWORD,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 1920,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.DEFENSIVE],
        description: "empty"
    },
    GREAT_AXE: {
        name: "Great Axe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 960,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: [WeaponQuality.HACK, WeaponQuality.IMPACT, WeaponQuality.TIRING],
        description: "empty"
    },
    FLAMBERGE_ZWEIHANDER: {
        name: "Flamberge Zweihander",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SWORD,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 7200,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.HACK, WeaponQuality.SLASH_2],
        description: "empty"
    },
    PICK: {
        name: "Pick",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 108,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.IMPALE, WeaponQuality.SLOW],
        description: "empty"
    },
    WARHAMMER_TH: {
        name: "Warhammer",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_MACE,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 720,
        enc: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        longReach: false,
        strBonus: true,
        damage: 6,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.PUMMEL, WeaponQuality.SLOW],
        description: "empty"
    },
    ZWEIHANDER: {
        name: "Zweihander",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SWORD,
        group: WeaponGroup.TWO_HANDED,
        groupLabel: WeaponGroupLabel.TWO_HANDED,
        price: 2400,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.HACK],
        description: "empty"
    }
};
// #endregion === WEAPONS MELEE SET === //
// === //
// #region ====== WEAPONS RANGED SET === //
TEW.DATABASE.WEAPONS.RANGED_SET = {
    ELF_BOW: {
        name: "Elf Bow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        twoHanded: true,
        price: 2400,
        enc: 2,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 150,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.PRECISE],
        description: "empty"
    },
    LONGBOW: {
        name: "Longbow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        twoHanded: true,
        price: 1200,
        enc: 3,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 100,
        strBonus: true,
        damage: 4,
        qualities: [WeaponQuality.DAMAGING],
        description: "empty"
    },
    BOW: {
        name: "Bow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        twoHanded: true,
        price: 960,
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 50,
        strBonus: true,
        damage: 3,
        qualities: [],
        description: "empty"
    },
    SHORTBOW: {
        name: "Shortbow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        twoHanded: true,
        price: 720,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 20,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "empty"
    },
    CROSSBOW_PISTOL: {
        name: "Crossbow Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CROSSBOW,
        group: WeaponGroup.CROSSBOW,
        groupLabel: WeaponGroupLabel.CROSSBOW,
        twoHanded: false,
        price: 1440,
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 10,
        strBonus: false,
        damage: 7,
        qualities: [WeaponQuality.PISTOL],
        description: "empty"
    },
    HEAVY_CROSSBOW: {
        name: "Heavy Crossbow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CROSSBOW,
        group: WeaponGroup.CROSSBOW,
        groupLabel: WeaponGroupLabel.CROSSBOW,
        twoHanded: true,
        price: 1680,
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 100,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DAMAGING, WeaponQuality.RELOAD_2],
        description: "empty"
    },
    CROSSBOW: {
        name: "Crossbow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CROSSBOW,
        group: WeaponGroup.CROSSBOW,
        groupLabel: WeaponGroupLabel.CROSSBOW,
        twoHanded: true,
        price: 1200,
        enc: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 60,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.RELOAD_1],
        description: "empty"
    },
    LASSO: {
        name: "Lasso",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_WHIP,
        group: WeaponGroup.ENTANGLING,
        groupLabel: WeaponGroupLabel.ENTANGLING,
        twoHanded: false,
        price: 72,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 6,
        strBonus: false,
        damage: 0,
        qualities: [WeaponQuality.ENTANGLE],
        description: "empty"
    },
    WHIP: {
        name: "Whip",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_WHIP,
        group: WeaponGroup.ENTANGLING,
        groupLabel: WeaponGroupLabel.ENTANGLING,
        twoHanded: false,
        price: 60,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 6,
        strBonus: true,
        damage: 2,
        qualities: [WeaponQuality.ENTANGLE],
        description: "empty"
    },
    SLING: {
        name: WeaponGroupLabel.SLING,
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        twoHanded: false,
        price: 12,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 60,
        strBonus: false,
        damage: 6,
        qualities: [],
        description: "empty"
    },
    STAFF_SLING: {
        name: "Staff Sling",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        twoHanded: true,
        price: 48,
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 100,
        strBonus: false,
        damage: 7,
        qualities: [],
        description: "empty"
    },
    BOLAS: {
        name: "Bolas",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CHAINS,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 12,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 9,
        strBonus: true,
        damage: 0,
        qualities: [WeaponQuality.ENTANGLE],
        description: "empty"
    },
    DART: {
        name: "Dart",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 24,
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 6,
        strBonus: true,
        damage: 1,
        qualities: [WeaponQuality.IMPALE],
        description: "empty"
    },
    JAVELIN: {
        name: "Javelin",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 126,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 9,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.IMPALE],
        description: "empty"
    },
    ROCK: {
        name: "Rock",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_GAUNTLET,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 0,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 9,
        strBonus: true,
        damage: 0,
        qualities: [],
        description: "empty"
    },
    THROWING_AXE: {
        name: "Throwing Axe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 240,
        enc: 1,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 6,
        strBonus: true,
        damage: 3,
        qualities: [WeaponQuality.HACK],
        description: "empty"
    },
    THROWING_KNIFE: {
        name: "Throwing Knife",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_KNIFE,
        group: WeaponGroup.THROWING,
        groupLabel: WeaponGroupLabel.THROWING,
        twoHanded: false,
        price: 216,
        enc: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: 6,
        strBonus: true,
        damage: 2,
        qualities: [],
        description: "empty"
    },
    BOMB: {
        name: "Bomb",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOMB,
        group: WeaponGroup.EXPLOSIVES,
        groupLabel: WeaponGroupLabel.EXPLOSIVES,
        twoHanded: false,
        price: 720,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 3,
        strBonus: false,
        damage: 12,
        qualities: [WeaponQuality.BLAST_5, WeaponQuality.DANGEROUS, WeaponQuality.IMPACT],
        description: "empty"
    },
    INCENDIARY: {
        name: "Incendiary",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOMB,
        group: WeaponGroup.EXPLOSIVES,
        groupLabel: WeaponGroupLabel.EXPLOSIVES,
        twoHanded: false,
        price: 240,
        enc: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 3,
        strBonus: false,
        damage: 0, // TODO
        qualities: [WeaponQuality.BLAST_4, WeaponQuality.DANGEROUS],
        description: "empty"
    },
    BLUNDERBUSS: {
        name: "Blunderbuss",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHOTGUN,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 480,
        enc: 1,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 20,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_2],
        description: "empty"
    },
    HOCHLAND_LONG_RIFLE: {
        name: "Hochland Long Rifle",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_RIFLE,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 24000,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 100,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.ACCURATE, WeaponQuality.PRECISE, WeaponQuality.RELOAD_4],
        description: "empty"
    },
    HANDGUN: {
        name: "Handgun",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 960,
        enc: 2,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: 50,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_3],
        description: "empty"
    },
    PISTOL: {
        name: "Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: false,
        price: 1920,
        enc: 0,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 20,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.PISTOL, WeaponQuality.RELOAD_1],
        description: "empty"
    },
    MATCHLOCK_HANDGUN: {
        name: "Matchlock Handgun",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 480,
        enc: 2,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 50,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_4],
        description: "empty"
    },
    MATCHLOCK_BLUNDERBUSS: {
        name: "Matchlock Blunderbuss",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SHOTGUN,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 240,
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 20,
        strBonus: false,
        damage: 7,
        qualities: [WeaponQuality.SPREAD_3, WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_3],
        description: "empty"
    },
    ARQUEBUS: {
        name: "Arquebus",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_RIFLE,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 1200,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 40,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_5],
        description: "empty"
    },
    DOUBLE_BARRELLED_HANDGUN: {
        name: "Double-Barrelled Handgun",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 1680,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 50,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.REPEATER, WeaponQuality.RELOAD_4],
        description: "empty"
    },
    GRIFFONSFOOT_PISTOL: {
        name: "Griffonsfoot Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: false,
        price: 2400,
        enc: 1,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 10,
        strBonus: false,
        damage: 7,
        qualities: [WeaponQuality.IMPRECISE, WeaponQuality.SPREAD_5, WeaponQuality.RELOAD_6],
        description: "empty"
    },
    GUN_AXE: {
        name: "GunAxe",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_AXE,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 1920,
        enc: 1,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 30,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_4],
        description: "empty"
    },
    GUN_HALBERD: {
        name: "Gun Halberd",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SPEAR,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        twoHanded: true,
        price: 2400,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 30,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_4],
        description: "empty"
    },
    REPEATER_HANDGUN: {
        name: "Repeater Handgun",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.ENGINEERING,
        groupLabel: WeaponGroupLabel.ENGINEERING,
        twoHanded: true,
        price: 2400,
        enc: 3,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 30,
        strBonus: false,
        damage: 9,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.RELOAD_5, WeaponQuality.REPEATER_4],
        description: "empty"
    },
    REPEATER_PISTOL: {
        name: "Repeater Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.ENGINEERING,
        groupLabel: WeaponGroupLabel.ENGINEERING,
        twoHanded: false,
        price: 3600,
        enc: 1,
        availability: Availability.RARE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_RARE,
        range: 10,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.PISTOL, WeaponQuality.RELOAD_4, WeaponQuality.REPEATER_4],
        description: "empty"
    },
    HAND_MORTAR: {
        name: "Hand Mortar",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.ENGINEERING,
        groupLabel: WeaponGroupLabel.ENGINEERING,
        twoHanded: true,
        price: 12000,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 30,
        strBonus: false,
        damage: 7,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_2],
        description: "empty"
    },
    CANE_PISTOL: {
        name: "Cane Pistol",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_PISTOL,
        group: WeaponGroup.ENGINEERING,
        groupLabel: WeaponGroupLabel.ENGINEERING,
        twoHanded: false,
        price: 3600,
        enc: 3,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: 10,
        strBonus: false,
        damage: 8,
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.RELOAD_6],
        description: "empty"
    }
};
// #endregion === WEAPONS RANGED SET === //
// === //
// #region ====== WEAPONS AMMO SET === //
TEW.DATABASE.WEAPONS.AMMO_SET = {
    ARROW: {
        name: "Arrow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 12,
        price: 60,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.IMPALE],
        description: "empty"
    },
    BARBED_ARROW: {
        name: "Barbed Arrow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 12,
        price: 96,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.SLASH_1],
        description: "empty"
    },
    BODKIN_ARROW: {
        name: "Bodkin Arrow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 12,
        price: 96,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "empty"
    },
    ELF_ARROW: {
        name: "Elf Arrow",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 1,
        price: 72,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: "+50",
        damage: "+1",
        qualities: [WeaponQuality.ACCURATE, WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "empty"
    },
    SHARO_STICK: {
        name: "Sharp Stick",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_BOW,
        group: WeaponGroup.BOW,
        groupLabel: WeaponGroupLabel.BOW,
        ammountSold: 1,
        price: 0,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "/2",
        damage: "-2",
        qualities: [WeaponQuality.DANGEROUS, WeaponQuality.IMPRECISE, WeaponQuality.UNDAMAGING],
        description: "empty"
    },
    BOLT: {
        name: "Bolt",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_CROSSBOW,
        group: WeaponGroup.CROSSBOW,
        groupLabel: WeaponGroupLabel.CROSSBOW,
        ammountSold: 12,
        price: 60,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.IMPALE],
        description: "empty"
    },
    LEAD_BULLET: {
        name: "Lead Bullet",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        ammountSold: 12,
        price: 4,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "-10",
        damage: "+1",
        qualities: [WeaponQuality.PUMMEL],
        description: "empty"
    },
    PEBBLE: {
        name: "Pebble",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        ammountSold: 1,
        price: 0,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "-10",
        damage: "-2",
        qualities: [WeaponQuality.IMPRECISE, WeaponQuality.UNDAMAGING],
        description: "empty"
    },
    STONE_BULLET: {
        name: "Stone Bullet",
        icon: TEW.DATABASE.ICONS.SET.WEAPON_SLING,
        group: WeaponGroup.SLING,
        groupLabel: WeaponGroupLabel.SLING,
        ammountSold: 12,
        price: 2,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.PUMMEL],
        description: "empty"
    },
    BULLET_AND_POWDER: {
        name: "Bullet and Powder",
        icon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 39,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+1",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "empty"
    },
    PAPER_CARTRIDGE: {
        name: "Paper Cartridge",
        icon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 60,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+1",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING, WeaponQuality.FASTER_RELOAD],
        description: "empty"
    },
    AQSHY_INFUSED_POWDER: {
        name: "Aqshy-Infused Powder",
        icon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 240,
        availability: Availability.EXOTIC,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_EXOTIC,
        range: "+10",
        damage: "+2",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING],
        description: "empty"
    },
    PRECISION_SHOT_AND_POWDER: {
        name: "Precision Shot and Powder",
        icon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 1,
        price: 36,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+1",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.PENETRATING, WeaponQuality.PRECISE],
        description: "empty"
    },
    IMPROVISED_SHOT_AND_POWDER: {
        name: "Improvised Shot and Powder",
        icon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 1,
        price: 3,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "/2",
        damage: "+0",
        qualities: [],
        description: "empty"
    },
    SMALL_SHOT_AND_POWDER: {
        name: "Small Shot and Powder",
        icon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 39,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "+0",
        damage: "+0",
        qualities: [WeaponQuality.SPREAD_3],
        description: "empty"
    },
    SCRAP_AND_POWDER: {
        name: "Scrap and Powder",
        icon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 24,
        availability: Availability.COMMON,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_COMMON,
        range: "/2",
        damage: "-1",
        qualities: [WeaponQuality.SPREAD_3, WeaponQuality.INFECTED],
        description: "empty"
    },
    LARGE_BULLET_AND_POWDER: {
        name: "Large Bullet and Powder",
        icon: TEW.DATABASE.ICONS.SET.PISTOL,
        group: WeaponGroup.BLACKPOWDER,
        groupLabel: WeaponGroupLabel.BLACKPOWDER,
        ammountSold: 12,
        price: 240,
        availability: Availability.SCARCE,
        availabilityIcon: TEW.DATABASE.ICONS.SET.AVAILABILITY_SCARCE,
        range: "+0",
        damage: "+2",
        qualities: [WeaponQuality.IMPALE, WeaponQuality.IMPACT, WeaponQuality.PENETRATING],
        description: "empty"
    }
};
// #endregion === WEAPONS AMMO SET === //
// === //
// #region ====== WEAPONS IDS === //
// The IDs are the keys of the SET objects MELE_SET, RANGED_SET
TEW.DATABASE.WEAPONS.IDS = Object.keys(TEW.DATABASE.WEAPONS.MELEE_SET)
        .concat(Object.keys(TEW.DATABASE.WEAPONS.RANGED_SET))
        .sort((a, b) => a.localeCompare(b));
// Those are the IDs of the groups
TEW.DATABASE.WEAPONS.GROUP_IDS = [
    "BASIC",
    "CAVALRY",
    "FENCING",
    "BRAWLING",
    "FLAIL",
    "PARRY",
    "POLE_ARM",
    "TWO_HANDED",
    "BOW",
    "CROSSBOW",
    "ENTANGLING",
    "SLING",
    "THROWING",
    "EXPLOSIVES",
    "BLACKPOWDER",
    "ENGINEERING"
];
// #endregion === WEAPONS IDS === //
// === //
// #region ====== WEAPONS ARRAY === //
// This is a 2D array, where the first element is the key and the second element is the value
TEW.DATABASE.WEAPONS.ARRAY = TEW.DATABASE.WEAPONS.IDS
        .map((key: string) => [key, TEW.DATABASE.WEAPONS.MELEE_SET[key] || TEW.DATABASE.WEAPONS.RANGED_SET[key]])
// #endregion === WEAPONS ARRAY === //


