TEW.MELEE_WEAPONS = TEW.MELEE_WEAPONS || {
    AXE: {
        name: "Axe",
        group: "BASIC",
        twoHanded: false,
        price: "0/10/0",
        enc: 1,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["HACK","UNBALANCED"]
    },
    BALLOCK_KNIFE: {
        name: "Ballock Knife",
        group: "BASIC",
        twoHanded: false,
        price: "0/16/0",
        enc: 0,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: ["IMPALE","PENETRATING","PRECISE"] //TODO if prone or surprised ?
    },
    CLUB: {
        name: "Club",
        group: "BASIC",
        twoHanded: false,
        price: "0/4/0",
        enc: 0,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["UNDAMAGING","UNBALANCED"]
    },
    DAGGER: {
        name: "Dagger",
        group: "BASIC",
        twoHanded: false,
        price: "0/16/0",
        enc: 0,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: []
    },
    IMPROVISED_WEAPON: {
        name: "Improvised Weapon",
        group: "BASIC",
        twoHanded: false,
        price: "0/0/0",
        enc: 1,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: ["UNDAMAGING","UNBALANCED"]
    },
    KNIFE: {
        name: "Knife",
        group: "BASIC",
        twoHanded: false,
        price: "0/8/0",
        enc: 0,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: ["UNDAMAGING"]
    },
    MACE: {
        name: "Mace",
        group: "BASIC",
        twoHanded: false,
        price: "0/15/0",
        enc: 1,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["PUMMEL","UNBALANCED"]
    },
    MILITARY_PICK: {
        name: "Military Pick",
        group: "BASIC",
        twoHanded: false,
        price: "0/15/0",
        enc: 1,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["PENETRATING","UNBALANCED"]
    },
    SCIMITAR: {
        name: "Scimitar",
        group: "BASIC",
        twoHanded: false,
        price: "1/0/0",
        enc: 1,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["SLASH_1"]
    },
    SWORD: {
        name: "Sword",
        group: "BASIC",
        twoHanded: false,
        price: "1/0/0",
        enc: 1,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: []
    },
    WARHAMMER: {
        name: "Warhammer",
        group: "BASIC",
        twoHanded: false,
        price: "1/0/0",
        enc: 1,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["PENETRATING","PUMMEL","UNBALANCED"] //TODO Penetrating OR Pummel
    },
    SHIELD_BUCKLER: {
        name: "Shield (Buckler)",
        group: "BASIC",
        twoHanded: false,
        price: "0/18/2",
        enc: 0,
        availability: "COMMON",
        reach: "Personnal",
        strBonus: true,
        damage: 1,
        qualities: ["SHIELD_1","DEFENSIVE","UNDAMAGING"]
    },
    SHIELD: {
        name: "Shield",
        group: "BASIC",
        twoHanded: false,
        price: "2/0/0",
        enc: 1,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["SHIELD_2","DEFENSIVE","UNDAMAGING"]
    },
    SHIELD_LARGE: {
        name: "Shield (Large)",
        group: "BASIC",
        twoHanded: false,
        price: "3/0/0",
        enc: 3,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["SHIELD_3","DEFENSIVE","UNDAMAGING"]
    },
    PAVISE: {
        name: "Pavise",
        group: "BASIC",
        twoHanded: false,
        price: "3/15/0",
        enc: 4,
        availability: "RARE",
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["SHIELD_5"]
    },
    CAVALRY_HAMMER: {
        name: "Cavalry Hammer (2H)",
        group: "CAVALRY",
        twoHanded: true,
        price: "3/0/0",
        enc: 3,
        availability: "SCARCE",
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["PUMMEL"]
    },
    DEMI_LANCE: { //TODO only when charge
        name: "Demi-Lance",
        group: "CAVALRY",
        twoHanded: false,
        price: "1/0/0",
        enc: 2,
        availability: "SCARCE",
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["IMPACT","IMPALE"]
    },
    LANCE: { //TODO only when charge
        name: "Lance",
        group: "CAVALRY",
        twoHanded: false,
        price: "1/0/0",
        enc: 3,
        availability: "RARE",
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: ["IMPACT","IMPALE"]
    },
    SABRE: {
        name: "Sabre",
        group: "CAVALRY",
        twoHanded: false,
        price: "0/10/0",
        enc: 1,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["SLASH_1"]
    },
    FOIL: {
        name: "Foil",
        group: "FENCING",
        twoHanded: false,
        price: "5/0/0",
        enc: 1,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["FAST","IMPALE","PRECISE","UNDAMAGING"]
    },
    RAPIER: {
        name: "Rapier",
        group: "FENCING",
        twoHanded: false,
        price: "5/0/0",
        enc: 1,
        availability: "SCARCE",
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["FAST","IMPALE"]
    },
    SMALLSWORD: {
        name: "Smallsword",
        group: "FENCING",
        twoHanded: false,
        price: "4/0/0",
        enc: 1,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["FAST","IMPALE","PRECISE"]
    },
    SPIKED_GAUNTLET: {
        name: "Spiked Gauntlet",
        group: "BRAWLING",
        twoHanded: false,
        price: "2/0/0",
        enc: 1,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["IMPALE","UNBALANCED"]
    },
    BOAT_HOOK: {
        name: "Boat Hook",
        group: "BRAWLING",
        twoHanded: false,
        price: "0/6/0",
        enc: 0,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 4,
        qualities: ["TRIP","UNDAMAGING"]
    },
    GARROTE: {
        name: "Garrote (2H)",
        group: "BRAWLING",
        twoHanded: true,
        price: "0/1/0",
        enc: 0,
        availability: "RARE",
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["ENTANGLE","SLOW","UNBALANCED","UNDAMAGING"]
    },
    UNARMED: {
        name: "Unarmed",
        group: "BRAWLING",
        twoHanded: false,
        price: "0/0/0",
        enc: 0,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: ["UNDAMAGING"]
    },
    KNUCKLEDUSTERS: {
        name: "Knuckledusters",
        group: "BRAWLING",
        twoHanded: false,
        price: "0/2/6",
        enc: 0,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: []
    },
    LOCKED_GAUNTLET: { //TODO
        name: "Locked Gauntlet",
        group: "BRAWLING",
        twoHanded: false,
        price: "1/0/0",
        enc: 1,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["UNDAMAGING"]
    },
    SAP: {
        name: "Sap",
        group: "BRAWLING",
        twoHanded: false,
        price: "0/1/0",
        enc: 0,
        availability: "RARE",
        longReach: false,
        strBonus: true,
        damage: 1,
        qualities: ["PUMMEL","UNBALANCED","UNDAMAGING"]
    },
    GRAIN_FLAIL: {
        name: "Grain Flail",
        group: "FLAIL",
        twoHanded: false,
        price: "0/10/0",
        enc: 1,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["DISTRACT","IMPRECISE","WRAP"]
    },
    FLAIL: {
        name: "Flail",
        group: "FLAIL",
        twoHanded: false,
        price: "2/0/0",
        enc: 1,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 5,
        qualities: ["DISTRACT","WRAP"]
    },
    MILITARY_FLAIL: {
        name: "Military Flail (2H)",
        group: "FLAIL",
        twoHanded: true,
        price: "3/0/0",
        enc: 2,
        availability: "RARE",
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: ["DISTRACT","IMPRECISE","TIRING","WRAP"]
    },
    CLOAK: {
        name: "Cloak",
        group: "PARRY",
        twoHanded: false,
        price: "0/10/0",
        enc: 1,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: ["ENTANGLE","DEFENSIVE","UNDAMAGING"]
    },
    MAIN_GAUCHE: {
        name: "Main Gauche",
        group: "PARRY",
        twoHanded: false,
        price: "1/0/0",
        enc: 0,
        availability: "RARE",
        longReach: false,
        strBonus: true,
        damage: 2,
        qualities: ["DEFENSIVE"]
    },
    SWORDBREAKER: {
        name: "Swordbreaker",
        group: "PARRY",
        twoHanded: false,
        price: "1/2/6",
        enc: 1,
        availability: "SCARCE",
        longReach: false,
        strBonus: true,
        damage: 3,
        qualities: ["DEFENSIVE","TRAP_BLADE"]
    },
    WEIGHTED_NET: {
        name: "Weighted Net (2H)",
        group: "PARRY",
        twoHanded: true,
        price: "0/10/0",
        enc: 1,
        availability: "RARE",
        longReach: false,
        strBonus: true,
        damage: 0,
        qualities: ["ENTANGLE","DEFENSIVE","SHIELD_1","SLOW","UNDAMAGING","WRAP"]
    },
    AHLSPIESS: {
        name: "Ahlspiess (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "2/0/0",
        enc: 2,
        availability: "SCARCE",
        longReach: true,
        strBonus: true,
        damage: 3,
        qualities: ["IMPALE","PENETRATING"]
    },
    BILL: {
        name: "Bill (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "2/0/0",
        enc: 3,
        availability: "SCARCE",
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE","HACK","TIRP"] //TODO Hack OR Trip
    },
    HALBERD: {
        name: "Halberd (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "2/0/0",
        enc: 3,
        availability: "COMMON",
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE","HACK","IMPALE"] //TODO Hack OR Impale
    },
    MANCATCHER: {
        name: "Mancatcher (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "2/0/0",
        enc: 3,
        availability: "RARE",
        longReach: true,
        strBonus: true,
        damage: 2,
        qualities: ["DEFENSIVE","ENTANGLE"]
    },
    PARTIZAN: {
        name: "Partizan (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "2/0/0",
        enc: 3,
        availability: "SCARCE",
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE","IMPALE","SLASH_2"] //TODO Impale OR Slash
    },
    POLLAXE: {
        name: "Pollaxe (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "2/0/0",
        enc: 3,
        availability: "SCARCE",
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE","HACK","IMPALE","PUMMEL"] //TODO Hack OR Impale OR Pummel
    },
    SPEAR: {
        name: "Spear (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "0/15/0",
        enc: 2,
        availability: "COMMON",
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["IMPALE"]
    },
    PIKE: {
        name: "Pike (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "0/18/0",
        enc: 4,
        availability: "RARE",
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["IMPALE"]
    },
    QUATERSTAFF: {
        name: "Quaterstaff (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "0/3/0",
        enc: 2,
        availability: "COMMON",
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE","PUMMEL"]
    },
    ENCHANTED_STAFF: {
        name: "Enchanted Staff (2H)",
        group: "POLEARM",
        twoHanded: true,
        price: "15/0/0",
        enc: 2,
        availability: "EXOTIC",
        longReach: true,
        strBonus: true,
        damage: 4,
        qualities: ["DEFENSIVE","PUMMEL"]
    },
    BASTARD_SWORD: {
        name: "Bastard Sword (2H)",
        group: "TWO_HANDED",
        twoHanded: true,
        price: "8/0/0",
        enc: 3,
        availability: "SCARCE",
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["DAMAGING","DEFENSIVE"]
    },
    GREAT_AXE: {
        name: "Great Axe (2H)",
        group: "TWO_HANDED",
        twoHanded: true,
        price: "4/0/0",
        enc: 3,
        availability: "COMMON",
        longReach: true,
        strBonus: true,
        damage: 6,
        qualities: ["HACK","IMPACT","TIRING"]
    },
    FLAMBERGE_ZWEIHANDER: {
        name: "Flamberge Zweihander (2H)",
        group: "TWO_HANDED",
        twoHanded: true,
        price: "30/0/0",
        enc: 3,
        availability: "EXOTIC",
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["DAMAGING","HACK","SLASH_2"]
    },
    PICK: {
        name: "Pick (2H)",
        group: "TWO_HANDED",
        twoHanded: true,
        price: "0/9/0",
        enc: 3,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 5,
        qualities: ["DAMAGING","IMPALE","SLOW"]
    },
    WARHAMMER_TH: {
        name: "Warhammer (2H)",
        group: "TWO_HANDED",
        twoHanded: true,
        price: "3/0/0",
        enc: 3,
        availability: "COMMON",
        longReach: false,
        strBonus: true,
        damage: 6,
        qualities: ["DAMAGING","PUMMEL","SLOW"]
    },
    ZWEIHANDER: {
        name: "Zweihander (2H)",
        group: "TWO_HANDED",
        twoHanded: true,
        price: "10/0/0",
        enc: 3,
        availability: "SCARCE",
        longReach: true,
        strBonus: true,
        damage: 5,
        qualities: ["DAMAGING","HACK"]
    }
}

TEW.RANGED_WEAPONS = TEW.RANGED_WEAPONS || {
    ELF_BOW: {
        name: "Elf Bow (2H)",
        group: "BOW",
        twoHanded: true,
        price: "10/0/0",
        enc: 2,
        availability: "EXOTIC",
        range: 150,
        strBonus: true,
        damage: 4,
        qualities: ["DAMAGING","PRECISE"]
    },
    LONGBOW: {
        name: "Longbow (2H)",
        group: "BOW",
        twoHanded: true,
        price: "5/0/0",
        enc: 3,
        availability: "SCARCE",
        range: 100,
        strBonus: true,
        damage: 4,
        qualities: ["DAMAGING"]
    },
    BOW: {
        name: "Bow (2H)",
        group: "BOW",
        twoHanded: true,
        price: "4/0/0",
        enc: 2,
        availability: "COMMON",
        range: 50,
        strBonus: true,
        damage: 3,
        qualities: []
    },
    SHORTBOW: {
        name: "Shortbow (2H)",
        group: "BOW",
        twoHanded: true,
        price: "3/0/0",
        enc: 1,
        availability: "COMMON",
        range: 20,
        strBonus: true,
        damage: 2,
        qualities: []
    },
    CROSSBOW_PISTOL: {
        name: "Crossbow Pistol",
        group: "CROSSBOW",
        twoHanded: false,
        price: "6/0/0",
        enc: 0,
        availability: "SCARCE",
        range: 10,
        strBonus: false,
        damage: 7,
        qualities: ["PISTOL"]
    },
    HEAVY_CROSSBOW: {
        name: "Heavy Crossbow (2H)",
        group: "CROSSBOW",
        twoHanded: true,
        price: "7/0/0",
        enc: 3,
        availability: "RARE",
        range: 100,
        strBonus: false,
        damage: 9,
        qualities: ["DAMAGING","RELOAD_2"]
    },
    CROSSBOW: {
        name: "Crossbow (2H)",
        group: "CROSSBOW",
        twoHanded: true,
        price: "5/0/0",
        enc: 2,
        availability: "COMMON",
        range: 60,
        strBonus: false,
        damage: 9,
        qualities: ["RELOAD_1"]
    }
}