name: Release

on:
  push:
    branches:
      - main

jobs:
  format-json:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Format JSON
        run: bash .github/workflow/format-json.sh
