name: Release

on:
  push:
    branches:
      - main

jobs:
  format-json:
    runs-on: ubuntu-latest
    steps:
      - name: Format JSON
        run: bash ${GITHUB_WORKSPACE}/.github/workflows/format-json.sh
