name: Release

on:
  push:
  workflow_dispatch:

jobs:
  format-json:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Format JSON
        run: bash format-json.sh
